CREATE TABLE IF NOT EXISTS AUTORES (
ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(200) NOT NULL,
BIOGRAFIA TEXT,
DATA_NASCIMENTO DATE,
NACIONALIDADE VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS USUARIOS (
ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOME_DE_USUARIO VARCHAR(50) NOT NULL UNIQUE,
EMAIL VARCHAR(100) NOT NULL UNIQUE,
SENHA_HASH VARCHAR(255) NOT NULL,
CRIADO_QUANDO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS MANGAS (
ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
TITULO VARCHAR(200) NOT NULL UNIQUE,
AUTORES_ID INT NOT NULL,
DATA_PUBLICACAO DATE,
SINOPSE TEXT,
CRIADO_QUANDO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
TIPO ENUM('MANGA', 'NOVEL') NOT NULL,
STATUS VARCHAR(50),
CAPA_URL VARCHAR(255),
FOREIGN KEY (AUTORES_ID) REFERENCES AUTORES(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS GENEROS (
ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(100) NOT NULL UNIQUE,
DESCRICAO TEXT
);

CREATE TABLE IF NOT EXISTS GENEROSMANGAS (
ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
MANGAS_ID INT NOT NULL,
GENEROS_ID INT NOT NULL,
FOREIGN KEY (MANGAS_ID) REFERENCES MANGAS(ID) ON DELETE CASCADE,
FOREIGN KEY (GENEROS_ID) REFERENCES GENEROS(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS RANKINGS (
ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
MANGAS_ID INT NOT NULL,
TIPO_RANKING ENUM('POPULARIDADE', 'AVALIACAO', 'VENDAS') NOT NULL,
POSICAO INT NOT NULL,
DATA_RANKING DATE NOT NULL,
FOREIGN KEY (MANGAS_ID) REFERENCES MANGAS(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS AVALIACOES (
ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
MANGAS_ID INT NOT NULL,
USUARIOS_ID INT NOT NULL,
NOTA INT CHECK (NOTA >= 1 AND NOTA <= 10),
COMENTARIO TEXT,
DATA_AVALIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (MANGAS_ID) REFERENCES MANGAS(ID) ON DELETE CASCADE,
FOREIGN KEY (USUARIOS_ID) REFERENCES USUARIOS(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS FAVORITOS (
ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
MANGAS_ID INT NOT NULL,
USUARIOS_ID INT NOT NULL,
DATA_ADICIONADO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (MANGAS_ID) REFERENCES MANGAS(ID) ON DELETE CASCADE,
FOREIGN KEY (USUARIOS_ID) REFERENCES USUARIOS(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS COMENTARIOSMANGA (
ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
MANGAS_ID INT NOT NULL,
USUARIOS_ID INT NOT NULL,
CONTEUDO TEXT NOT NULL,
DATA_COMENTARIO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (MANGAS_ID) REFERENCES MANGAS(ID) ON DELETE CASCADE,
FOREIGN KEY (USUARIOS_ID) REFERENCES USUARIOS(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS CAPITULOS (
ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
MANGAS_ID INT NOT NULL,
NUMERO_CAPITULO VARCHAR(20) NOT NULL,
TITULO_CAPITULO VARCHAR(200),
DATA_LANCAMENTO DATE,
SINOPSE TEXT,
CRIADO_QUANDO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (MANGAS_ID) REFERENCES MANGAS(ID) ON DELETE CASCADE
);
