-- SENHA NORMAL: 'USER01' 
-- SENHA NORMAL: 'USER02' 
-- SENHA NORMAL: 'USER03' 
-- SENHA NORMAL: 'USER04' 
-- SENHA NORMAL: 'USER05' 
-- SENHA NORMAL: 'USER06' 
-- SENHA NORMAL: 'USER07' 
-- SENHA NORMAL: 'USER08' 
-- SENHA NORMAL: 'USER09' 
-- SENHA NORMAL: 'USER10' 
-- SENHA NORMAL: 'USER11' 
-- SENHA NORMAL: 'USER12' 
-- SENHA NORMAL: 'USER13' 
-- SENHA NORMAL: 'USER14' 
-- SENHA NORMAL: 'USER15' 
-- SENHA NORMAL: 'USER16' 
-- SENHA NORMAL: 'USER17' 
-- SENHA NORMAL: 'USER18' 
-- SENHA NORMAL: 'USER19' 
-- SENHA NORMAL: 'USER20' 
-- SENHA NORMAL: 'USER21' 
-- SENHA NORMAL: 'USER22' 
-- SENHA NORMAL: 'USER23' 
-- SENHA NORMAL: 'USER24' 
-- SENHA NORMAL: 'USER25' 
-- SENHA NORMAL: 'USER26' 
-- SENHA NORMAL: 'USER27' 
-- SENHA NORMAL: 'USER28' 
-- SENHA NORMAL: 'USER29' 
-- SENHA NORMAL: 'USER30'
INSERT INTO AUTORES (NOME, BIOGRAFIA, DATA_NASCIMENTO, NACIONALIDADE) VALUES
    ('Eiichiro Oda', 'Mangaká japonês, criador de One Piece.', '1975-01-01', 'Japonês'),
    ('Masashi Kishimoto', 'Mangaká japonês, criador de Naruto.', '1974-11-08', 'Japonês'),
    ('Hajime Isayama', 'Mangaká japonês, criador de Attack on Titan.', '1986-08-29', 'Japonês'),
    ('Rumiko Takahashi', 'Mangaká japonesa conhecida por Ranma ½ e Inuyasha.', '1957-10-10', 'Japonesa'),
    ('Koyoharu Gotouge', 'Mangaká responsável por Demon Slayer: Kimetsu no Yaiba.', NULL, 'Japonês'),
    ('Yoshihiro Togashi', 'Mangaká japonês, criador de Hunter x Hunter e Yu Yu Hakusho.', '1966-04-27', 'Japonês'),
    ('Tite Kubo', 'Mangaká japonês, criador de Bleach.', '1977-06-26', 'Japonês'),
    ('Akira Toriyama', 'Mangaká japonês, criador de Dragon Ball.', '1955-04-05', 'Japonês'),
    ('CLAMP', 'Grupo de mangakás conhecido por Cardcaptor Sakura e xxxHOLiC.', NULL, 'Japonês'),
    ('Naoko Takeuchi', 'Mangaká japonesa, criadora de Sailor Moon.', '1967-03-15', 'Japonesa'),
    ('Kentaro Miura', 'Mangaká japonês, criador original de Berserk.', '1966-07-11', 'Japonês'),
    ('Yana Toboso', 'Mangaká japonesa conhecida por Black Butler.', '1984-01-24', 'Japonesa'),
    ('Kosuke Fujishima', 'Mangaká japonês, criador de Ah! My Goddess e Youre Under Arrest.', '1964-07-07', 'Japonês'),
    ('Sui Ishida', 'Mangaká japonês, criador de Tokyo Ghoul.', NULL, 'Japonês'),
    ('Tsugumi Ohba e Takeshi Obata', 'Dupla associada a Death Note e Bakuman: Ohba no roteiro e Obata na arte.', NULL, 'Japonês'),
    ('Kaiu Shirai e Posuka Demizu', 'Dupla responsável por The Promised Neverland: Shirai no roteiro e Demizu na arte.', NULL, 'Japonês'),
    ('Kohei Horikoshi', 'Mangaká japonês, criador de My Hero Academia.', '1986-11-20', 'Japonês'),
    ('Gege Akutami', 'Mangaká responsável por Jujutsu Kaisen.', NULL, 'Japonês'),
    ('Hiro Mashima', 'Mangaká japonês conhecido por Fairy Tail.', '1977-05-03', 'Japonês'),
    ('Hiromu Arakawa', 'Mangaká japonesa, criadora de Fullmetal Alchemist.', '1973-05-08', 'Japonesa'),
    ('Atsushi Ohkubo', 'Mangaká japonês, criador de Soul Eater e Fire Force.', '1979-09-20', 'Japonês'),
    ('Yūki Tabata', 'Mangaká japonês, criador de Black Clover.', '1984-07-30', 'Japonês'),
    ('Katsura Hoshino', 'Mangaká japonesa, autora de D.Gray-man.', '1980-04-21', 'Japonesa'),
    ('Hideaki Sorachi', 'Mangaká japonês, criador de Gintama.', '1979-05-25', 'Japonês'),
    ('Takehiko Inoue', 'Mangaká japonês, criador de Vagabond e Slam Dunk.', '1967-01-12', 'Japonês'),
    ('Norihiro Yagi', 'Mangaká japonês, autor de Claymore.', '1968-12-18', 'Japonês'),
    ('Adachitoka', 'Dupla de mangakás conhecida por Noragami.', NULL, 'Japonês'),
    ('Kazue Kato', 'Mangaká japonesa, criadora de Blue Exorcist.', '1980-07-20', 'Japonesa'),
    ('Akira Amano', 'Mangaká japonesa, autora de Katekyo Hitman Reborn!.', '1973-06-22', 'Japonesa'),
    ('Hiroyuki Takei', 'Mangaká japonês, criador de Shaman King.', '1972-05-15', 'Japonês'),
    ('ONE', 'Mangaká japonês conhecido por Mob Psycho 100 e One Punch Man.', NULL, 'Japonês'),
    ('Akihito Tsukushi', 'Mangaká japonês, criador de Made in Abyss.', NULL, 'Japonês'),
    ('Negi Haruba', 'Mangaká japonês, autor de The Quintessential Quintuplets.', '1991-07-27', 'Japonês'),
    ('Kei Sanbe', 'Mangaká japonês, criador de Erased.', '1975-03-05', 'Japonês'),
    ('Aka Akasaka', 'Mangaká japonês, autor de Kaguya-sama: Love is War.', '1988-08-29', 'Japonês'),
    ('Fuse', 'Autor japonês de That Time I Got Reincarnated as a Slime.', NULL, 'Japonês'),
    ('Reki Kawahara', 'Autor japonês de Sword Art Online e Accel World.', '1974-08-17', 'Japonês'),
    ('Kugane Maruyama', 'Autor japonês de Overlord.', NULL, 'Japonês'),
    ('Tappei Nagatsuki', 'Autor japonês de Re:Zero - Starting Life in Another World.', '1987-03-11', 'Japonês'),
    ('Aneko Yusagi', 'Autor japonês de The Rising of the Shield Hero.', NULL, 'Japonês');

INSERT INTO USUARIOS (NOME_DE_USUARIO, EMAIL, SENHA_HASH) VALUES
('mangafan123', 'megafan123@example.com', '$2y$10$nAtqNT0xzjM.IheNjtWPpOqtXZVBZXpF1y.DV.efWqDr.DMq43zTO'),
('otakulover', 'otakulovers@example.com', '$2y$10$5MIPebCfnkvM8yxqmLBRFOsTAS.u2zrxfscdsG8L4xbnLVe66u4ui'),
('devmaster', 'devmaster@example.com', '$2y$10$lPJNgJ549BrKcq0yEOjXv.8OoUmTNIEcHBWIzZS86ZvyKMSxzIiQO'),
('codewizard', 'codewizard@example.com', '$2y$10$idRy3qs8h867Gltta9lIPuws.ags3F5Sx/wZJpmEyg4wecAD7gQWO'),
('pixelartist', 'pixelartist@example.com', '$2y$10$v4QcIlSCGjSiZe089wVFYeuTLoWwMErO0N66gruErs6YkLYA8LFXS'),
('darkknight', 'darkknight@example.com', '$2y$10$.0wsArxFz8KmKs075hNBQucfmeNMDYy374Hmal.0QAYT5LFwIbmo.'),
('sunsetgirl', 'sunsetgirl@example.com', '$2y$10$40SJ.VlsffhSl6E11msTyO/cmP9miUEi6onzqM8OrAsT6yasY.J4O'),
('nightwolf', 'nightwolf@example.com', '$2y$10$8W3HvVxxkso5Ey9ULrIXmuG3WbTQ1dDTVSXu/FNOeNajlD.NEJe8S'),
('techgeek', 'techgeek@example.com', '$2y$10$Pw7WmQxhHw4.h4r1OO.2aeiOeRlqxI0KDF0JV2piTB6Q2/K.prV2S'),
('gamersoul', 'gamersoul@example.com', '$2y$10$xOFMhuFTc7YoLRpbeNSZ/OnwBdMHGdCahNbvKStGFlQFp3blddLe6'),
('retroplayer', 'retroplayer@example.com', '$2y$10$uEb7mHe0ElaqYgIMBjHg3.bccDKw48BAgwVnMCHBnaXAkEv9OZlYm'),
('speedrunner', 'speedrunner@example.com', '$2y$10$9OGA6eoHTBRAiUA2l8384.7CfHu2eazbH.eEo.8EzsHeY22w0llpW'),
('cloudthinker', 'cloudthinker@example.com', '$2y$10$qoOK1E4P6E8cvayGPRTSUeRiN9d5AS38NrLP.Gsk1hsUVx/Q4gc5e'),
('silentcoder', 'silentcoder@example.com', '$2y$10$u0P8uha.PtfgssVHWjhafecSuTR8VFKuDr9I5nTx5Z2iWCoJKJhqW'),
('redphoenix', 'redphoenix@example.com', '$2y$10$hkfI3JP/m4/.ixf1.CMBmeXoebR7RHVKihR83sibF/gllc3ZmWk1m'),
('bluehorizon', 'bluehorizon@example.com', '$2y$10$yrYgeTtGoO1tVepRrhgYJeYb4.E3lSNB5ADzJEBfyO9psZmvSvm22'),
('ironmind', 'ironmind@example.com', '$2y$10$WEk6FoWM3LucOnm2iJCf2e/Z168IjHCfx02vy2QcbtKv4MT2QXKNy'),
('lazycat', 'lazycat@example.com', '$2y$10$svuoPl3wW2VUHaRsy8CKn.5oS7HU/HYiyQ7eki.KohXMVFYiP3Fdq'),
('stormbringer', 'stormbringer@example.com', '$2y$10$HbMkYW90ZsF9qyt00eJXlO9aR3JKuKtoKRFojSdcML18NLFH/Rn0i'),
('voidwalker', 'voidwalker@example.com', '$2y$10$z3.rN4prCgGZiL51t3xyD.JlesUdkBCRt28KWSLr2P3fDFGz5q31m'),
('dataminer', 'dataminer@example.com', '$2y$10$V0v4S4KGMUTa9hAND72zMeTDX9Z/BZfwPHBNSuECs.opKVYRrjMoW'),
('bitcrusher', 'bitcrusher@example.com', '$2y$10$sHL1PikWitAfcPiWraOj3OJv0j2A00O56RURaZ2Wm2KJH1DboWvmG'),
('logicloop', 'logicloop@example.com', '$2y$10$zppqSbrZAgw4/L5BIp5UBOOzrNVG8SgK6IiIqHNqoXALFGT9vELDq'),
('stacktrace', 'stacktrace@example.com', '$2y$10$fLoQGtREa0GSFTv.MsA6QeoM2KsphgkSfVeHdP1TWG/kA6ovMN/ey'),
('bytehunter', 'bytehunter@example.com', '$2y$10$u/4UtKDWyW85fqYDsWMa/.8Gc6gtltKRufB.oE.ktDBRQXWOKtcFu'),
('kernelpanic', 'kernelpanic@example.com', '$2y$10$koudmXIEfesUY9qqrNZ.EOkb5LDykt3CBO6tOI1O/xHEJ4PCD/eJS'),
('scriptkid', 'scriptkid@example.com', '$2y$10$pZORijUW9U36jjqHqVclEeWcB9JW9eSMO4xOywpxfoctO0PmZCQaG'),
('phantomuser', 'phantomuser@example.com', '$2y$10$6IjejYShJtl9.wyHKJf5Xu5jCEty5Od7ogRtrBfAAxqs6g4ZE4qUO'),
('neonshadow', 'neonshadow@example.com', '$2y$10$8.R2IbJK2yWhaUzISGysGO654f5A6apewImA3zlR1QwHGw30jrzgm'),
('frostbyte', 'frostbyte@example.com', '$2y$10$89kgHnQLgyCVdsKSIvrg1e1b1z6svUlL1lNKqCv1M1eWBJhZk/B1u');

INSERT INTO MANGAS (TITULO, AUTORES_ID, DATA_PUBLICACAO, SINOPSE, TIPO, STATUS, CAPA_URL) VALUES
    ('One Piece', '1', '1997-07-22', 'A aventura de Monkey D. Luffy e dos Piratas do Chapéu de Palha em busca do tesouro One Piece.', 'MANGA', 'Em andamento', 'imagens/capas_seed/one-piece.jpg'),
    ('Naruto', '2', '1999-09-21', 'Naruto Uzumaki busca reconhecimento em sua vila e sonha em se tornar Hokage.', 'MANGA', 'Concluído', 'imagens/capas_seed/naruto.jpg'),
    ('Attack on Titan', '3', '2009-09-09', 'A humanidade luta pela sobrevivência contra criaturas gigantes conhecidas como Titãs.', 'MANGA', 'Concluído', 'imagens/capas_seed/attack-on-titan.jpg'),
    ('Demon Slayer: Kimetsu no Yaiba', '5', '2016-02-15', 'Tanjiro Kamado enfrenta demônios para salvar sua irmã Nezuko.', 'MANGA', 'Concluído', 'imagens/capas_seed/demon-slayer-kimetsu-no-yaiba.jpg'),
    ('Bleach', '7', '2001-08-07', 'Ichigo Kurosaki recebe poderes de Ceifador de Almas e passa a enfrentar ameaças espirituais.', 'MANGA', 'Concluído', 'imagens/capas_seed/bleach.jpg'),
    ('Dragon Ball', '8', '1984-12-03', 'Goku vive aventuras, treina artes marciais e procura as Esferas do Dragão.', 'MANGA', 'Concluído', 'imagens/capas_seed/dragon-ball.jpg'),
    ('Tokyo Ghoul', '14', '2011-09-08', 'Kaneki Ken se torna meio humano e meio ghoul após um encontro que muda sua vida.', 'MANGA', 'Concluído', 'imagens/capas_seed/tokyo-ghoul.jpg'),
    ('Death Note', '15', '2003-12-01', 'Light Yagami encontra um caderno sobrenatural capaz de matar pessoas pelo nome.', 'MANGA', 'Concluído', 'imagens/capas_seed/death-note.jpg'),
    ('Berserk', '11', '1989-08-25', 'Guts atravessa um mundo brutal de fantasia sombria marcado por guerra, ambição e monstros.', 'MANGA', 'Em andamento', 'imagens/capas_seed/berserk.jpg'),
    ('Sailor Moon', '10', '1991-12-28', 'Usagi Tsukino desperta como uma guerreira mágica destinada a proteger o mundo.', 'MANGA', 'Concluído', 'imagens/capas_seed/sailor-moon.jpg'),
    ('Hunter x Hunter', '6', '1998-03-03', 'Gon Freecss busca se tornar Hunter e encontrar seu pai.', 'MANGA', 'Hiato', 'imagens/capas_seed/hunter-x-hunter.jpg'),
    ('Black Butler (Kuroshitsuji)', '12', '2006-09-16', 'Ciel Phantomhive faz um pacto com um mordomo demoníaco para buscar vingança.', 'MANGA', 'Em andamento', 'imagens/capas_seed/black-butler-kuroshitsuji.jpg'),
    ('Ah! My Goddess', '13', '1988-08-25', 'A vida de Keiichi Morisato muda quando ele conhece a deusa Belldandy.', 'MANGA', 'Concluído', 'imagens/capas_seed/ah-my-goddess.jpg'),
    ('Cardcaptor Sakura', '9', '1996-05-01', 'Sakura Kinomoto precisa capturar cartas mágicas que escaparam de um livro misterioso.', 'MANGA', 'Concluído', 'imagens/capas_seed/cardcaptor-sakura.jpg'),
    ('Ranma ½', '4', '1987-08-19', 'Ranma Saotome vive confusões depois de passar a se transformar ao contato com água fria.', 'MANGA', 'Concluído', 'imagens/capas_seed/ranma-12.jpg'),
    ('Inuyasha', '4', '1996-11-13', 'Kagome Higurashi viaja para o Japão feudal e encontra o meio-demônio Inuyasha.', 'MANGA', 'Concluído', 'imagens/capas_seed/inuyasha.jpg'),
    ('Yu Yu Hakusho', '6', '1990-12-03', 'Yusuke Urameshi torna-se detetive espiritual após morrer salvando uma criança.', 'MANGA', 'Concluído', 'imagens/capas_seed/yu-yu-hakusho.jpg'),
    ('xxxHOLiC', '9', '2003-02-24', 'Kimihiro Watanuki trabalha para Yuko Ichihara, uma mulher capaz de realizar desejos.', 'MANGA', 'Concluído', 'imagens/capas_seed/xxxholic.webp'),
    ('Youre Under Arrest', '13', '1986-11-01', 'Duas policiais enfrentam casos e confusões em uma delegacia de trânsito.', 'MANGA', 'Concluído', 'imagens/capas_seed/youre-under-arrest.jpg'),
    ('Bakuman', '15', '2008-08-11', 'Dois jovens aspirantes a mangakás tentam alcançar sucesso na indústria de mangás.', 'MANGA', 'Concluído', 'imagens/capas_seed/bakuman.jpg'),
    ('The Promised Neverland', '16', '2016-08-01', 'Crianças descobrem o segredo de seu orfanato e planejam uma fuga perigosa.', 'MANGA', 'Concluído', 'imagens/capas_seed/the-promised-neverland.jpg'),
    ('My Hero Academia', '17', '2014-07-07', 'Izuku Midoriya entra em uma escola para heróis em um mundo dominado por superpoderes.', 'MANGA', 'Concluído', 'imagens/capas_seed/my-hero-academia.jpg'),
    ('Jujutsu Kaisen', '18', '2018-03-05', 'Yuji Itadori entra no mundo das maldições após ingerir um objeto amaldiçoado.', 'MANGA', 'Concluído', 'imagens/capas_seed/jujutsu-kaisen.jpg'),
    ('Fairy Tail', '19', '2006-08-02', 'A guilda Fairy Tail vive aventuras mágicas cheias de amizade e batalhas.', 'MANGA', 'Concluído', 'imagens/capas_seed/fairy-tail.jpg'),
    ('Fullmetal Alchemist', '20', '2001-07-12', 'Dois irmãos alquimistas buscam a Pedra Filosofal para recuperar seus corpos.', 'MANGA', 'Concluído', 'imagens/capas_seed/fullmetal-alchemist.webp'),
    ('Soul Eater', '21', '2004-05-12', 'Estudantes treinam armas vivas e artesãos em uma academia comandada pela Morte.', 'MANGA', 'Concluído', 'imagens/capas_seed/soul-eater.jpg'),
    ('Black Clover', '22', '2015-02-16', 'Asta e Yuno competem para se tornar o Rei Mago em um mundo movido por magia.', 'MANGA', 'Em andamento', 'imagens/capas_seed/black-clover.jpg'),
    ('D.Gray-man', '23', '2004-05-31', 'Allen Walker combate Akuma usando uma arma anti-Akuma chamada Inocência.', 'MANGA', 'Em andamento', 'imagens/capas_seed/d-gray-man.jpg'),
    ('Gintama', '24', '2003-12-08', 'Gintoki Sakata vive aventuras cômicas em um Japão alternativo dominado por alienígenas.', 'MANGA', 'Concluído', 'imagens/capas_seed/gintama.jpg'),
    ('Vagabond', '25', '1998-09-03', 'A obra acompanha uma versão ficcional da vida do espadachim Miyamoto Musashi.', 'MANGA', 'Hiato', 'imagens/capas_seed/vagabond.jpg'),
    ('Claymore', '26', '2001-05-08', 'Guerreiras meio-humanas enfrentam monstros devoradores de pessoas conhecidos como Yoma.', 'MANGA', 'Concluído', 'imagens/capas_seed/claymore.jpg'),
    ('Noragami', '27', '2010-12-06', 'Yato, um deus menor, tenta ganhar seguidores e mudar seu destino.', 'MANGA', 'Concluído', 'imagens/capas_seed/noragami.jpg'),
    ('Blue Exorcist', '28', '2009-04-04', 'Rin Okumura descobre ser filho de Satanás e decide se tornar exorcista.', 'MANGA', 'Em andamento', 'imagens/capas_seed/blue-exorcist.jpg'),
    ('Katekyo Hitman Reborn!', '29', '2004-05-24', 'Tsuna Sawada descobre que foi escolhido para herdar uma família mafiosa.', 'MANGA', 'Concluído', 'imagens/capas_seed/katekyo-hitman-reborn.jpg'),
    ('Shaman King', '30', '1998-06-30', 'Yoh Asakura compete para se tornar o Rei dos Xamãs.', 'MANGA', 'Concluído', 'imagens/capas_seed/shaman-king.jpg'),
    ('Mob Psycho 100', '31', '2012-04-18', 'Shigeo Kageyama, um jovem com poderes psíquicos, tenta levar uma vida normal.', 'MANGA', 'Concluído', 'imagens/capas_seed/mob-psycho-100.jpg'),
    ('Made in Abyss', '32', '2012-10-20', 'Riko desce ao Abismo em busca de sua mãe e descobre seus perigos.', 'MANGA', 'Em andamento', 'imagens/capas_seed/made-in-abyss.jpg'),
    ('The Quintessential Quintuplets', '33', '2017-08-09', 'Um tutor ajuda cinco irmãs gêmeas a melhorar seus estudos.', 'MANGA', 'Concluído', 'imagens/capas_seed/the-quintessential-quintuplets.jpg'),
    ('Erased', '34', '2012-06-04', 'Satoru Fujinuma volta no tempo para impedir uma tragédia de sua infância.', 'MANGA', 'Concluído', 'imagens/capas_seed/erased.jpg'),
    ('Kaguya-sama: Love is War', '35', '2015-05-19', 'Dois estudantes tentam fazer o outro confessar amor primeiro em uma disputa psicológica.', 'MANGA', 'Concluído', 'imagens/capas_seed/kaguya-sama-love-is-war.jpg'),
    ('That Time I Got Reincarnated as a Slime', '36', '2013-05-30', 'Um homem reencarna como slime em um mundo de fantasia e constrói uma nova comunidade.', 'NOVEL', 'Em andamento', 'imagens/capas_seed/that-time-i-got-reincarnated-as-a-slime.jpg'),
    ('Sword Art Online', '37', '2009-04-10', 'Jogadores são presos em um MMORPG de realidade virtual onde morrer no jogo significa morrer de verdade.', 'NOVEL', 'Em andamento', 'imagens/capas_seed/sword-art-online.jpg'),
    ('Overlord', '38', '2012-07-30', 'Um jogador fica preso como seu avatar poderoso em um mundo inspirado em um MMORPG.', 'NOVEL', 'Em andamento', 'imagens/capas_seed/overlord.jpg'),
    ('Re:Zero - Starting Life in Another World', '39', '2014-01-25', 'Subaru Natsuki é levado a outro mundo e descobre que retorna no tempo ao morrer.', 'NOVEL', 'Em andamento', 'imagens/capas_seed/re-zero-starting-life-in-another-world.jpg'),
    ('The Rising of the Shield Hero', '40', '2013-08-22', 'Naofumi Iwatani é convocado para outro mundo como o Herói do Escudo.', 'NOVEL', 'Em andamento', 'imagens/capas_seed/the-rising-of-the-shield-hero.jpg');

INSERT INTO GENEROS (NOME, DESCRICAO) VALUES
    ('Ação', 'Cenas de combate, perseguição e conflitos físicos.'),
    ('Aventura', 'Jornadas, exploração e progressão de mundo.'),
    ('Comédia', 'Situações voltadas ao humor e entretenimento leve.'),
    ('Drama', 'Conflitos emocionais, perdas e crescimento dos personagens.'),
    ('Fantasia', 'Elementos mágicos, criaturas ou mundos imaginários.'),
    ('Romance', 'Relacionamentos amorosos como parte importante da obra.'),
    ('Terror', 'Medo, ameaça, violência gráfica ou atmosfera assustadora.'),
    ('Ficção Científica', 'Tecnologia, ciência especulativa ou futuros alternativos.'),
    ('Mistério', 'Enigmas, investigações e segredos a serem descobertos.'),
    ('Slice of Life', 'Rotina, convivência e acontecimentos cotidianos.'),
    ('Esporte', 'Competições e atividades esportivas.'),
    ('Histórico', 'Ambientação baseada em períodos históricos.'),
    ('Sobrenatural', 'Fenômenos espirituais, maldições, demônios ou poderes inexplicáveis.'),
    ('Mecha', 'Robôs gigantes ou máquinas de combate.'),
    ('Artes Marciais', 'Lutas, treinamento físico e técnicas de combate.'),
    ('Psicológico', 'Conflitos mentais, manipulação e tensão interna.'),
    ('Suspense', 'Tensão contínua e expectativa sobre o próximo acontecimento.'),
    ('Escolar', 'Histórias ambientadas em escola ou com vida estudantil relevante.'),
    ('Isekai', 'Personagens transportados, presos ou reencarnados em outro mundo.'),
    ('Magia', 'Sistema de magia, feitiços ou usuários de poderes mágicos.'),
    ('Super-heróis', 'Heróis, vilões e poderes especiais em contexto heroico.'),
    ('Samurai', 'Espadachins, ronins ou cultura guerreira japonesa.'),
    ('Fantasia Sombria', 'Fantasia com tom pesado, cruel ou macabro.'),
    ('Policial', 'Polícia, crimes, investigação ou rotina de agentes públicos.'),
    ('Shounen', 'Obras associadas ao público jovem masculino e revistas shounen.'),
    ('Seinen', 'Obras voltadas a público adulto ou jovem adulto.'),
    ('Magical Girl', 'Garotas mágicas, transformação e poderes de heroína.'),
    ('Shoujo', 'Obras associadas ao público jovem feminino e revistas shoujo.');

INSERT INTO GENEROSMANGAS (MANGAS_ID, GENEROS_ID) VALUES
    ('1', '1'),
    ('1', '2'),
    ('1', '3'),
    ('1', '5'),
    ('1', '25'),
    ('2', '1'),
    ('2', '2'),
    ('2', '15'),
    ('2', '5'),
    ('2', '25'),
    ('3', '1'),
    ('3', '4'),
    ('3', '9'),
    ('3', '17'),
    ('3', '23'),
    ('3', '26'),
    ('4', '1'),
    ('4', '2'),
    ('4', '4'),
    ('4', '5'),
    ('4', '13'),
    ('4', '25'),
    ('5', '1'),
    ('5', '2'),
    ('5', '5'),
    ('5', '13'),
    ('5', '25'),
    ('6', '1'),
    ('6', '2'),
    ('6', '3'),
    ('6', '15'),
    ('6', '5'),
    ('6', '25'),
    ('7', '1'),
    ('7', '4'),
    ('7', '7'),
    ('7', '13'),
    ('7', '16'),
    ('7', '17'),
    ('7', '26'),
    ('8', '4'),
    ('8', '9'),
    ('8', '13'),
    ('8', '16'),
    ('8', '17'),
    ('8', '26'),
    ('9', '1'),
    ('9', '2'),
    ('9', '4'),
    ('9', '7'),
    ('9', '23'),
    ('9', '26'),
    ('10', '2'),
    ('10', '5'),
    ('10', '6'),
    ('10', '13'),
    ('10', '27'),
    ('10', '28'),
    ('11', '1'),
    ('11', '2'),
    ('11', '5'),
    ('11', '25'),
    ('12', '4'),
    ('12', '9'),
    ('12', '13'),
    ('12', '17'),
    ('12', '23'),
    ('12', '26'),
    ('13', '3'),
    ('13', '5'),
    ('13', '6'),
    ('13', '13'),
    ('13', '26'),
    ('14', '2'),
    ('14', '5'),
    ('14', '6'),
    ('14', '13'),
    ('14', '27'),
    ('14', '28'),
    ('15', '1'),
    ('15', '3'),
    ('15', '6'),
    ('15', '15'),
    ('15', '25'),
    ('16', '1'),
    ('16', '2'),
    ('16', '4'),
    ('16', '5'),
    ('16', '6'),
    ('16', '13'),
    ('16', '25'),
    ('17', '1'),
    ('17', '2'),
    ('17', '3'),
    ('17', '13'),
    ('17', '15'),
    ('17', '25'),
    ('18', '4'),
    ('18', '9'),
    ('18', '5'),
    ('18', '13'),
    ('18', '16'),
    ('18', '26'),
    ('19', '1'),
    ('19', '3'),
    ('19', '24'),
    ('19', '26'),
    ('20', '3'),
    ('20', '4'),
    ('20', '10'),
    ('20', '18'),
    ('20', '25'),
    ('21', '4'),
    ('21', '9'),
    ('21', '16'),
    ('21', '17'),
    ('21', '25'),
    ('22', '1'),
    ('22', '3'),
    ('22', '18'),
    ('22', '21'),
    ('22', '25'),
    ('23', '1'),
    ('23', '4'),
    ('23', '13'),
    ('23', '23'),
    ('23', '25'),
    ('24', '1'),
    ('24', '2'),
    ('24', '3'),
    ('24', '5'),
    ('24', '20'),
    ('24', '25'),
    ('25', '1'),
    ('25', '2'),
    ('25', '4'),
    ('25', '5'),
    ('25', '25'),
    ('26', '1'),
    ('26', '3'),
    ('26', '5'),
    ('26', '13'),
    ('26', '25'),
    ('27', '1'),
    ('27', '2'),
    ('27', '3'),
    ('27', '5'),
    ('27', '20'),
    ('27', '25'),
    ('28', '1'),
    ('28', '4'),
    ('28', '13'),
    ('28', '23'),
    ('28', '25'),
    ('29', '1'),
    ('29', '3'),
    ('29', '8'),
    ('29', '12'),
    ('29', '25'),
    ('30', '1'),
    ('30', '4'),
    ('30', '12'),
    ('30', '15'),
    ('30', '22'),
    ('30', '26'),
    ('31', '1'),
    ('31', '2'),
    ('31', '4'),
    ('31', '5'),
    ('31', '7'),
    ('31', '23'),
    ('31', '25'),
    ('32', '1'),
    ('32', '3'),
    ('32', '5'),
    ('32', '13'),
    ('32', '25'),
    ('33', '1'),
    ('33', '5'),
    ('33', '13'),
    ('33', '25'),
    ('34', '1'),
    ('34', '3'),
    ('34', '13'),
    ('34', '24'),
    ('34', '25'),
    ('35', '1'),
    ('35', '2'),
    ('35', '13'),
    ('35', '25'),
    ('36', '1'),
    ('36', '3'),
    ('36', '10'),
    ('36', '13'),
    ('36', '16'),
    ('36', '25'),
    ('37', '2'),
    ('37', '4'),
    ('37', '5'),
    ('37', '7'),
    ('37', '17'),
    ('37', '26'),
    ('38', '3'),
    ('38', '6'),
    ('38', '10'),
    ('38', '18'),
    ('38', '25'),
    ('39', '4'),
    ('39', '9'),
    ('39', '16'),
    ('39', '17'),
    ('39', '26'),
    ('40', '3'),
    ('40', '6'),
    ('40', '16'),
    ('40', '18'),
    ('40', '26'),
    ('41', '1'),
    ('41', '2'),
    ('41', '3'),
    ('41', '5'),
    ('41', '19'),
    ('42', '1'),
    ('42', '2'),
    ('42', '6'),
    ('42', '8'),
    ('42', '19'),
    ('43', '1'),
    ('43', '5'),
    ('43', '19'),
    ('43', '23'),
    ('44', '4'),
    ('44', '5'),
    ('44', '16'),
    ('44', '19'),
    ('45', '1'),
    ('45', '2'),
    ('45', '4'),
    ('45', '5'),
    ('45', '19');

INSERT INTO RANKINGS (MANGAS_ID, TIPO_RANKING, POSICAO, DATA_RANKING) VALUES
(1, 'POPULARIDADE', 1, '2024-01-01'),
(2, 'POPULARIDADE', 2, '2024-01-01'),
(3, 'POPULARIDADE', 3, '2024-01-01'),
(4, 'POPULARIDADE', 4, '2024-01-01'),
(5, 'POPULARIDADE', 5, '2024-01-01'),
(6, 'POPULARIDADE', 6, '2024-01-01'),
(7, 'POPULARIDADE', 7, '2024-01-01'),
(8, 'POPULARIDADE', 8, '2024-01-01'),
(9, 'POPULARIDADE', 9, '2024-01-01'),
(10, 'POPULARIDADE', 10, '2024-01-01'),
(1, 'AVALIACAO', 1, '2024-01-01'),
(2, 'AVALIACAO', 2, '2024-01-01'),
(3, 'AVALIACAO', 3, '2024-01-01'),
(4, 'AVALIACAO', 4, '2024-01-01'),
(5, 'AVALIACAO', 5, '2024-01-01'),
(6, 'AVALIACAO', 6, '2024-01-01'),
(7, 'AVALIACAO', 7, '2024-01-01'),
(8, 'AVALIACAO', 8, '2024-01-01'),
(9, 'AVALIACAO', 9, '2024-01-01'),
(10, 'AVALIACAO', 10, '2024-01-01'),
(1, 'VENDAS', 1, '2024-01-01'),
(2, 'VENDAS', 2, '2024-01-01'),
(3, 'VENDAS', 3, '2024-01-01'),
(4, 'VENDAS', 4, '2024-01-01'),
(5, 'VENDAS', 5, '2024-01-01'),
(6, 'VENDAS', 6, '2024-01-01'),
(7, 'VENDAS', 7, '2024-01-01'),
(8, 'VENDAS', 8, '2024-01-01'),
(9, 'VENDAS', 9, '2024-01-01'),
(10, 'VENDAS', 10, '2024-01-01');

INSERT INTO AVALIACOES (MANGAS_ID, USUARIOS_ID, NOTA, COMENTARIO) VALUES
(1, 1, 9, 'Incrível história e personagens cativantes!'),
(2, 2, 8, 'Adorei a arte e o enredo.'),
(3, 3, 10, 'Um dos melhores mangás que já li!'),
(4, 4, 7, 'Boa leitura, mas poderia ser melhor desenvolvida.'),
(5, 5, 9, 'Personagens profundos e trama envolvente.'),
(6, 1, 8, 'Gostei muito dos temas abordados.'),
(7, 2, 10, 'Simplesmente fantástico!'),
(8, 3, 7, 'Interessante, mas com alguns clichês.'),
(9, 4, 9, 'Ação e aventura na medida certa.'),
(10, 5, 8, 'Recomendo para fãs do gênero.'),
(11, 1, 10, 'Arte impressionante e história emocionante.'),
(12, 2, 9, 'Muito bom, mas alguns personagens poderiam ser mais explorados.'),
(13, 3, 8, 'Leitura agradável e fluida.'),
(14, 4, 10, 'Um clássico que todo fã deve ler.'),
(15, 5, 9, 'Trama envolvente e personagens memoráveis.'),
(1, 1, 9, 'Continuação à altura do primeiro volume!'),
(2, 2, 8, 'Gostei, mas esperava mais reviravoltas.'),
(3, 3, 10, 'Incrível desenvolvimento dos personagens!'),
(4, 4, 7, 'Boa leitura, mas faltou algo a mais.'),
(5, 5, 9, 'Ação constante e bem escrita.'),
(6, 1, 8, 'Adorei os novos personagens introduzidos.'),
(7, 2, 10, 'Simplesmente espetacular!'),
(8, 3, 7, 'Algumas partes foram um pouco lentas.'),
(9, 4, 9, 'Muito emocionante e cheio de surpresas.'),
(10, 5, 8, 'Recomendo para quem gosta de ação.'),
(11, 1, 10, 'Arte ainda melhor que o primeiro volume!'),
(12, 2, 9, 'História envolvente e bem construída.'),
(13, 3, 8, 'Leitura agradável e divertida.'),
(14, 4, 10, 'Um must-read para qualquer fã de mangás.'),
(15, 5, 9, 'Trama sólida e personagens cativantes.'),
(1, 1, 9, 'Terceiro volume à altura dos anteriores!'),
(2, 2, 8, 'Gostei, mas esperava mais ação.'),
(3, 3, 10, 'Desenvolvimento incrível dos personagens!'),
(4, 4, 7, 'Boa leitura, mas faltou algo especial.'),
(5, 5, 9, 'Ação constante e bem escrita.'),
(6, 1, 8, 'Novos personagens interessantes.'),
(7, 2, 10, 'Simplesmente espetacular!'),
(8, 3, 7, 'Algumas partes foram um pouco lentas.'),
(9, 4, 9, 'Muito emocionante e cheio de surpresas.'),
(10, 5, 8, 'Recomendo para quem gosta de ação.'),
(11, 1, 10, 'Arte ainda melhor que os volumes anteriores!'),
(12, 2, 9, 'História envolvente e bem construída.'),
(13, 3, 8, 'Leitura agradável e divertida.'),
(14, 4, 10, 'Um must-read para qualquer fã de mangás.'),
(15, 5, 9, 'Trama sólida e personagens cativantes.'),
(1, 1, 9, 'Quarto volume que mantém a qualidade!'),
(2, 2, 8, 'Gostei, mas esperava mais desenvolvimento.'),
(3, 3, 10, 'Personagens cada vez mais profundos!'),
(4, 4, 7, 'Boa leitura, mas faltou algo especial.'),
(5, 5, 9, 'Ação constante e bem escrita.'),
(6, 1, 8, 'Novos personagens interessantes.'),
(7, 2, 10, 'Simplesmente espetacular!'),
(8, 3, 7, 'Algumas partes foram um pouco lentas.'),
(9, 4, 9, 'Muito emocionante e cheio de surpresas.'),
(10, 5, 8, 'Recomendo para quem gosta de ação.'),
(11, 1, 10, 'Arte ainda melhor que os volumes anteriores!'),
(12, 2, 9, 'História envolvente e bem construída.'),
(13, 3, 8, 'Leitura agradável e divertida.'),
(14, 4, 10, 'Um must-read para qualquer fã de mangás.'),
(15, 5, 9, 'Trama sólida e personagens cativantes.'),
(1, 1, 10, 'Quinto volume épico! Mal posso esperar pelo próximo.'),
(2, 2, 9, 'Gostei muito do desenvolvimento da história.'),
(3, 3, 10, 'Personagens cada vez mais profundos e interessantes!'),
(4, 4, 8, 'Boa leitura, mas esperava mais ação.'),
(5, 5, 9, 'Ação constante e bem escrita.'),
(6, 1, 9, 'Novos personagens adicionam muito à trama.'),
(7, 2, 10, 'Simplesmente espetacular!'),
(8, 3, 8, 'Algumas partes foram um pouco lentas.'),
(9, 4, 9, 'Muito emocionante e cheio de surpresas.'),
(10, 5, 9, 'Recomendo para quem gosta de ação.'),
(11, 1, 10, 'Arte impressionante e história emocionante.'),
(12, 2, 9, 'Muito bom, mas alguns personagens poderiam ser mais explorados.'),
(13, 3, 8, 'Leitura agradável e fluida.'),
(14, 4, 10, 'Um clássico que todo fã deve ler.'),
(15, 5, 9, 'Trama envolvente e personagens memoráveis.'),
(16, 1, 9, 'Excelente mangá com uma história única!'),
(17, 2, 8, 'Gostei muito dos personagens e do enredo.'),
(18, 3, 10, 'Um dos melhores mangás que já li!'),
(19, 4, 7, 'Boa leitura, mas poderia ser melhor desenvolvida.'),
(20, 5, 9, 'Personagens profundos e trama envolvente.'),
(21, 1, 8, 'Gostei muito dos temas abordados.'),
(22, 2, 10, 'Simplesmente fantástico!'),
(23, 3, 7, 'Interessante, mas com alguns clichês.'),
(24, 4, 9, 'Ação e aventura na medida certa.'),
(25, 5, 8, 'Recomendo para fãs do gênero.'),
(26, 1, 10, 'Arte impressionante e história emocionante.'),
(27, 2, 9, 'Muito bom, mas alguns personagens poderiam ser mais explorados.'),
(28, 3, 8, 'Leitura agradável e fluida.'),
(29, 4, 10, 'Um clássico que todo fã deve ler.'),
(30, 5, 9, 'Trama envolvente e personagens memoráveis.'),
(31, 1, 9, 'Incrível história e personagens cativantes!'),
(32, 2, 8, 'Adorei a arte e o enredo.'),
(33, 3, 10, 'Um dos melhores mangás que já li!'),
(34, 4, 7, 'Boa leitura, mas poderia ser melhor desenvolvida.'),
(35, 5, 9, 'Personagens profundos e trama envolvente.'),
(36, 1, 8, 'Gostei muito dos temas abordados.'),
(37, 2, 10, 'Simplesmente fantástico!'),
(38, 3, 7, 'Interessante, mas com alguns clichês.'),
(39, 4, 9, 'Ação e aventura na medida certa.'),
(40, 5, 8, 'Recomendo para fãs do gênero.'),
(1, 2, 9, 'Continuação à altura do primeiro volume!'),
(2, 3, 8, 'Gostei, mas esperava mais reviravoltas.'),
(3, 4, 10, 'Incrível desenvolvimento dos personagens!'),
(4, 5, 7, 'Boa leitura, mas faltou algo a mais.'),
(5, 1, 9, 'Ação constante e bem escrita.'),
(6, 2, 8, 'Adorei os novos personagens introduzidos.'),
(7, 3, 10, 'Simplesmente espetacular!'),
(8, 4, 7, 'Algumas partes foram um pouco lentas.'),
(9, 5, 9, 'Muito emocionante e cheio de surpresas.'),
(10, 1, 8, 'Recomendo para quem gosta de ação.'),
(11, 2, 10, 'Arte ainda melhor que o primeiro volume!'),
(12, 3, 9, 'História envolvente e bem construída.'),
(13, 4, 8, 'Leitura agradável e divertida.'),
(14, 5, 10, 'Um must-read para qualquer fã de mangás.'),
(15, 1, 9, 'Trama sólida e personagens cativantes.'),
(16, 2, 9, 'Excelente mangá com uma história única!'),
(17, 3, 8, 'Gostei muito dos personagens e do enredo.'),
(18, 4, 10, 'Um dos melhores mangás que já li!'),
(19, 5, 7, 'Boa leitura, mas poderia ser melhor desenvolvida.'),
(20, 1, 9, 'Personagens profundos e trama envolvente.'),
(21, 2, 8, 'Gostei muito dos temas abordados.'),
(22, 3, 10, 'Simplesmente fantástico!'),
(23, 4, 7, 'Interessante, mas com alguns clichês.'),
(24, 5, 9, 'Ação e aventura na medida certa.'),
(25, 1, 8, 'Recomendo para fãs do gênero.'),
(26, 2, 10, 'Arte impressionante e história emocionante.'),
(27, 3, 9, 'Muito bom, mas alguns personagens poderiam ser mais explorados.'),
(28, 4, 8, 'Leitura agradável e fluida.'),
(29, 5, 10, 'Um clássico que todo fã deve ler.'),
(30, 1, 9, 'Trama envolvente e personagens memoráveis.'),
(31, 2, 9, 'Incrível história e personagens cativantes!'),
(32, 3, 8, 'Adorei a arte e o enredo.'),
(33, 4, 10, 'Um dos melhores mangás que já li!'),
(34, 5, 7, 'Boa leitura, mas poderia ser melhor desenvolvida.'),
(35, 1, 9, 'Personagens profundos e trama envolvente.'),
(36, 2, 8, 'Gostei muito dos temas abordados.'),
(37, 3, 10, 'Simplesmente fantástico!'),
(38, 4, 7, 'Interessante, mas com alguns clichês.'),
(39, 5, 9, 'Ação e aventura na medida certa.'),
(40, 1, 8, 'Recomendo para fãs do gênero.'),
(1, 3, 9, 'Terceiro volume à altura dos anteriores!'),
(2, 4, 8, 'Gostei, mas esperava mais ação.'),
(3, 5, 10, 'Desenvolvimento incrível dos personagens!'),
(4, 1, 7, 'Boa leitura, mas faltou algo especial.'),
(5, 2, 9, 'Ação constante e bem escrita.'),
(6, 3, 8, 'Novos personagens interessantes.'),
(7, 4, 10, 'Simplesmente espetacular!'),
(8, 5, 7, 'Algumas partes foram um pouco lentas.'),
(9, 1, 9, 'Muito emocionante e cheio de surpresas.'),
(10, 2, 8, 'Recomendo para quem gosta de ação.'),
(11, 3, 10, 'Arte ainda melhor que os volumes anteriores!'),
(12, 4, 9, 'História envolvente e bem construída.'),
(13, 5, 8, 'Leitura agradável e divertida.'),
(14, 1, 10, 'Um must-read para qualquer fã de mangás.'),
(15, 2, 9, 'Trama sólida e personagens cativantes.'),
(16, 3, 9, 'Excelente mangá com uma história única!'),
(17, 4, 8, 'Gostei muito dos personagens e do enredo.'),
(18, 5, 10, 'Um dos melhores mangás que já li!'),
(19, 1, 7, 'Boa leitura, mas poderia ser melhor desenvolvida.'),
(20, 2, 9, 'Personagens profundos e trama envolvente.'),
(21, 3, 8, 'Gostei muito dos temas abordados.'),
(22, 4, 10, 'Simplesmente fantástico!'),
(23, 5, 7, 'Interessante, mas com alguns clichês.'),
(24, 1, 9, 'Ação e aventura na medida certa.'),
(25, 2, 8, 'Recomendo para fãs do gênero.'),
(26, 3, 10, 'Arte impressionante e história emocionante.'),
(27, 4, 9, 'Muito bom, mas alguns personagens poderiam ser mais explorados.'),
(28, 5, 8, 'Leitura agradável e fluida.'),
(29, 1, 10, 'Um clássico que todo fã deve ler.'),
(30, 2, 9, 'Trama envolvente e personagens memoráveis.'),
(31, 3, 9, 'Incrível história e personagens cativantes!'),
(32, 4, 8, 'Adorei a arte e o enredo.'),
(33, 5, 10, 'Um dos melhores mangás que já li!'),
(34, 1, 7, 'Boa leitura, mas poderia ser melhor desenvolvida.'),
(35, 2, 9, 'Personagens profundos e trama envolvente.'),
(36, 3, 8, 'Gostei muito dos temas abordados.'),
(37, 4, 10, 'Simplesmente fantástico!'),
(38, 5, 7, 'Interessante, mas com alguns clichês.'),
(39, 1, 9, 'Ação e aventura na medida certa.'),
(40, 2, 8, 'Recomendo para fãs do gênero.'),
(1, 4, 9, 'Quarto volume que mantém a qualidade!'),
(2, 5, 8, 'Gostei, mas esperava mais desenvolvimento.'),
(3, 1, 10, 'Personagens cada vez mais profundos!'),
(4, 2, 7, 'Boa leitura, mas faltou algo especial.'),
(5, 3, 9, 'Ação constante e bem escrita.'),
(6, 4, 8, 'Novos personagens interessantes.'),
(7, 5, 10, 'Simplesmente espetacular!'),
(8, 1, 7, 'Algumas partes foram um pouco lentas.'),
(9, 2, 9, 'Muito emocionante e cheio de surpresas.'),
(10, 3, 8, 'Recomendo para quem gosta de ação.'),
(11, 4, 10, 'Arte ainda melhor que os volumes anteriores!'),
(12, 5, 9, 'História envolvente e bem construída.'),
(13, 1, 8, 'Leitura agradável e divertida.'),
(14, 2, 10, 'Um must-read para qualquer fã de mangás.'),
(15, 3, 9, 'Trama sólida e personagens cativantes.'),
(16, 4, 9, 'Excelente mangá com uma história única!'),
(17, 5, 8, 'Gostei muito dos personagens e do enredo.'),
(18, 1, 10, 'Um dos melhores mangás que já li!'),
(19, 2, 7, 'Boa leitura, mas poderia ser melhor desenvolvida.'),
(20, 3, 9, 'Personagens profundos e trama envolvente.'),
(21, 4, 8, 'Gostei muito dos temas abordados.'),
(22, 5, 10, 'Simplesmente fantástico!'),
(23, 1, 7, 'Interessante, mas com alguns clichês.'),
(24, 2, 9, 'Ação e aventura na medida certa.'),
(25, 3, 8, 'Recomendo para fãs do gênero.'),
(26, 4, 10, 'Arte impressionante e história emocionante.'),
(27, 5, 9, 'Muito bom, mas alguns personagens poderiam ser mais explorados.'),
(28, 1, 8, 'Leitura agradável e fluida.'),
(29, 2, 10, 'Um clássico que todo fã deve ler.'),
(30, 3, 9, 'Trama envolvente e personagens memoráveis.'),
(31, 4, 9, 'Incrível história e personagens cativantes!'),
(32, 5, 8, 'Adorei a arte e o enredo.'),
(33, 1, 10, 'Um dos melhores mangás que já li!'),
(34, 2, 7, 'Boa leitura, mas poderia ser melhor desenvolvida.'),
(35, 3, 9, 'Personagens profundos e trama envolvente.'),
(36, 4, 8, 'Gostei muito dos temas abordados.'),
(37, 5, 10, 'Simplesmente fantástico!'),
(38, 1, 7, 'Interessante, mas com alguns clichês.'),
(39, 2, 9, 'Ação e aventura na medida certa.'),
(40, 3, 8, 'Recomendo para fãs do gênero.');




INSERT INTO FAVORITOS (MANGAS_ID, USUARIOS_ID) VALUES
(1, 1),
(2, 1),
(3, 2),
(4, 2),
(5, 3),
(6, 3),
(7, 4),
(8, 4),
(9, 5),
(10, 5),
(11, 1),
(12, 2),
(13, 3),
(14, 4),
(15, 5),
(1, 2),
(2, 3),
(3, 4),
(4, 5),
(5, 1),
(6, 2),
(7, 3),
(8, 4),
(9,21),
(8,20),
(7,19),
(6,18),
(5,17),
(4,16),
(3,15),
(2,14),
(1,13),
(10,12),
(11,11),
(12,10),
(13,9),
(14,8),
(15,7),
(1,6),
(2,5),
(3,4),
(4,3),
(5,2),
(6,1),
(7,5),
(8,4),
(9,3),
(10,2),
(11,1),
(12,5),
(13,4),
(14,3),
(15,2),
(16,1),
(17,2),
(18,3),
(19,4),
(20,5),
(21,1),
(22,2),
(23,3),
(24,4),
(25,5),
(26,1),
(27,2),
(28,3),
(29,4),
(30,5),
(31,1),
(32,2),
(33,3),
(34,4),
(35,5),
(36,1),
(37,2),
(38,3),
(39,4),
(40,5),
(1,4),
(2,3),
(3,2),
(4,1),
(5,5),
(6,4),
(7,3),
(8,2),
(9,1),
(10,5),
(11,4),
(12,3),
(13,2),
(14,1),
(15,5),
(16,4),
(17,3),
(18,2),
(19,1),
(20,5),
(21,4),
(22,3),
(23,2),
(24,1),
(25,5),
(26,4),
(27,3),
(28,2),
(29,1),
(30,5),
(31,4),
(32,3),
(33,2),
(34,1),
(35,5),
(36,4),
(37,3),
(38,2),
(39,1),
(40,5),
(1,5),
(2,4),
(3,3),
(4,2),
(5,1),
(6,5),
(7,4),
(8,3),
(9,2),
(10,1),
(11,5),
(12,4),
(13,3),
(14,2),
(15,1),
(16,5),
(17,4),
(18,3),
(19,2),
(20,1),
(21,5),
(22,4),
(23,3),
(24,2),
(25,1),
(26,5),
(27,4),
(28,3),
(29,2),
(30,1),
(31,5),
(32,4),
(33,3),
(34,2),
(35,1),
(36,5),
(37,4),
(38,3),
(39,2),
(40,1),
(1,1),
(2,2),
(3,3),
(4,4),
(5,5),
(6,1),
(7,2),
(8,3),
(9,4),
(10,5),
(11,1),
(12,2),
(13,3),
(14,4),
(15,5),
(16,1),
(17,2),
(18,3),
(19,4),
(20,5),
(21,1),
(22,2),
(23,3),
(24,4),
(25,5),
(26,1),
(27,2),
(28,3),
(29,4),
(30,5),
(31,1),
(32,2),
(33,3),
(34,4),
(35,5),
(36,1),
(37,2),
(38,3),
(39,4),
(40,5);

INSERT INTO COMENTARIOSMANGA (MANGAS_ID, USUARIOS_ID, CONTEUDO) VALUES
(1, 1, 'Esse mangá é incrível! A história me prendeu desde o primeiro capítulo.'),
(2, 2, 'Adorei os personagens e a arte é fantástica.'),
(3, 3, 'Um dos melhores mangás que já li na vida!'),
(4, 4, 'A trama é envolvente e cheia de reviravoltas.'),
(5, 5, 'Recomendo para todos os fãs de mangás de ação.'),
(1, 2, 'O desenvolvimento dos personagens é excelente.'),
(2, 3, 'A história é cativante e cheia de emoção.'),
(3, 4, 'Não consegui parar de ler até terminar!'),
(4, 5, 'A arte é detalhada e muito bem feita.'),
(5, 1, 'Mal posso esperar pelo próximo volume!'),
(6, 2, 'A narrativa é fluida e fácil de acompanhar.'),
(7, 3, 'Os diálogos são muito bem escritos.'),
(8, 4, 'A ambientação do mangá é incrível.'),
(9, 5, 'Cada capítulo é melhor que o anterior.'),
(10, 1, 'Os vilões são muito bem construídos.'),
(11, 2, 'A ação é constante e emocionante.'),
(12, 3, 'Os personagens secundários também são interessantes.'),
(13, 4, 'A história tem um ritmo perfeito.'),
(14, 5, 'A arte evolui muito ao longo do mangá.'),
(15, 1, 'Um mangá que todo fã deve ler pelo menos uma vez.'),
(6, 3, 'A trama é cheia de surpresas e reviravoltas.'),
(7, 4, 'Os personagens têm profundidade e complexidade.'),
(8, 5, 'A história é emocionante e tocante.'),
(9, 1, 'A arte é simplesmente deslumbrante.'),
(10, 2, 'Cada capítulo me deixou ansioso pelo próximo.'),
(11, 3, 'Os temas abordados são muito relevantes.'),
(12, 4, 'A narrativa é envolvente e cativante.'),
(13, 5, 'Os personagens são memoráveis e únicos.'),
(14, 1, 'A história é cheia de ação e aventura.'),
(15, 2, 'Um mangá que eu recomendo para todos os meus amigos.'),
(1, 3, 'A trama é complexa e muito bem desenvolvida.'),
(2, 4, 'Os personagens têm uma química incrível.'),
(3, 5, 'A arte é detalhada e cheia de vida.'),
(4, 1, 'Cada capítulo é uma nova surpresa.'),
(5, 2, 'A história é emocionante e cheia de reviravoltas.'),
(6, 4, 'Os personagens são profundos e bem construídos.'),
(7, 5, 'A narrativa é fluida e fácil de seguir.'),
(8, 1, 'A ambientação do mangá é fantástica.'),
(9, 2, 'Cada capítulo me deixou querendo mais.'),
(10, 3, 'Os vilões são complexos e interessantes.'),
(11, 4, 'A ação é constante e emocionante.'),
(12, 5, 'Os personagens secundários são tão interessantes quanto os principais.'),
(13, 1, 'A história tem um ritmo perfeito e envolvente.'),
(14, 2, 'A arte evolui muito ao longo do mangá.'),
(15, 3, 'Um mangá que todo fã deve ler pelo menos uma vez na vida.'),
(16, 4, 'A trama é cheia de surpresas e reviravoltas.'),
(17, 5, 'Os personagens têm profundidade e complexidade.'),
(18, 1, 'A história é emocionante e tocante.'),
(19, 2, 'A arte é simplesmente deslumbrante.'),
(20, 3, 'Cada capítulo me deixou ansioso pelo próximo.'),
(21, 4, 'Os temas abordados são muito relevantes.'),
(22, 5, 'A narrativa é envolvente e cativante.'),
(23, 1, 'Os personagens são memoráveis e únicos.'),
(24, 2, 'A história é cheia de ação e aventura.'),
(25, 3, 'Um mangá que eu recomendo para todos os meus amigos.'),
(26, 4, 'A trama é complexa e muito bem desenvolvida.'),
(27, 5, 'Os personagens têm uma química incrível.'),
(28, 1, 'A arte é detalhada e cheia de vida.'),
(29, 2, 'Cada capítulo é uma nova surpresa.'),
(30, 3, 'A história é emocionante e cheia de reviravoltas.'),
(31, 4, 'Os personagens são profundos e bem construídos.'),
(32, 5, 'A narrativa é fluida e fácil de seguir.'),
(33, 1, 'A ambientação do mangá é fantástica.'),
(34, 2, 'Cada capítulo me deixou querendo mais.'),
(35, 3, 'Os vilões são complexos e interessantes.'),
(36, 4, 'A ação é constante e emocionante.'),
(37, 5, 'Os personagens secundários são tão interessantes quanto os principais.'),
(38, 1, 'A história tem um ritmo perfeito e envolvente.'),
(39, 2, 'A arte evolui muito ao longo do mangá.'),
(40, 3, 'Um mangá que todo fã deve ler pelo menos uma vez na vida.'),
(1, 4, 'Incrível mangá! A história e os personagens são fantásticos.'),
(2, 5, 'Adorei a arte e o enredo. Mal posso esperar pelo próximo volume.'),
(3, 1, 'Um dos melhores mangás que já li! A trama é envolvente.'),
(4, 2, 'Ação e aventura na medida certa. Recomendo muito!'),
(5, 3, 'Personagens profundos e uma história cativante. Vale a pena ler.'),
(6, 4, 'A narrativa é fluida e fácil de acompanhar. Gostei muito!'),
(7, 5, 'Os diálogos são muito bem escritos e os personagens são memoráveis.'),
(8, 1, 'A ambientação do mangá é incrível. Cada capítulo é melhor que o anterior.'),
(9, 2, 'Os vilões são muito bem construídos. Ação constante e emocionante!'),
(10, 3, 'Mal posso esperar pelo próximo volume! A arte é impressionante.'),
(11, 4, 'Muito bom, mas alguns personagens poderiam ser mais explorados.'),
(12, 5, 'Leitura agradável e fluida. A história é envolvente.'),
(13, 1, 'Um clássico que todo fã deve ler. Trama envolvente e personagens memoráveis.'),
(14, 2, 'Incrível história e personagens cativantes! Adorei a arte e o enredo.'),
(15, 3, 'Um dos melhores mangás que já li! A trama é profunda e emocionante.'),
(16, 4, 'Boa leitura, mas poderia ser melhor desenvolvida. Personagens profundos e trama envolvente.'),
(17, 5, 'Gostei muito dos temas abordados. Simplesmente fantástico!'),
(18, 1, 'Interessante, mas com alguns clichês. Ação e aventura na medida certa.'),
(19, 2, 'Recomendo para fãs do gênero. Arte impressionante e história emocionante.'),
(20, 3, 'Muito bom, mas alguns personagens poderiam ser mais explorados. Leitura agradável e fluida.'),
(21, 4, 'Um clássico que todo fã deve ler. Trama envolvente e personagens memoráveis.'),
(22, 5, 'Incrível história e personagens cativantes! Adorei a arte e o enredo.'),
(23, 1, 'Um dos melhores mangás que já li! A trama é profunda e emocionante.'),
(24, 2, 'Boa leitura, mas poderia ser melhor desenvolvida. Personagens profundos e trama envolvente.'),
(25, 3, 'Gostei muito dos temas abordados. Simplesmente fantástico!'),
(26, 4, 'Interessante, mas com alguns clichês. Ação e aventura na medida certa.'),
(27, 5, 'Recomendo para fãs do gênero. Arte impressionante e história emocionante.'),
(28, 1, 'Muito bom, mas alguns personagens poderiam ser mais explorados. Leitura agradável e fluida.'),
(29, 2, 'Um clássico que todo fã deve ler. Trama envolvente e personagens memoráveis.'),
(30, 3, 'Incrível história e personagens cativantes! Adorei a arte e o enredo.'),
(31, 4, 'Um dos melhores mangás que já li! A trama é profunda e emocionante.'),
(32, 5, 'Boa leitura, mas poderia ser melhor desenvolvida. Personagens profundos e trama envolvente.'),
(33, 1, 'Gostei muito dos temas abordados. Simplesmente fantástico!'),
(34, 2, 'Interessante, mas com alguns clichês. Ação e aventura na medida certa.'),
(35, 3, 'Recomendo para fãs do gênero. Arte impressionante e história emocionante.'),
(36, 4, 'Muito bom, mas alguns personagens poderiam ser mais explorados. Leitura agradável e fluida.'),
(37, 5, 'Um clássico que todo fã deve ler. Trama envolvente e personagens memoráveis.'),
(38, 1, 'Incrível história e personagens cativantes! Adorei a arte e o enredo.'),
(39, 2, 'Um dos melhores mangás que já li! A trama é profunda e emocionante.'),
(40, 3, 'Boa leitura, mas poderia ser melhor desenvolvida. Personagens profundos e trama envolvente.'),
(1, 5, 'Gostei muito dos temas abordados. Simplesmente fantástico!'),
(2, 4, 'Interessante, mas com alguns clichês. Ação e aventura na medida certa.'),
(3, 3, 'Recomendo para fãs do gênero. Arte impressionante e história emocionante.'),
(4, 2, 'Muito bom, mas alguns personagens poderiam ser mais explorados. Leitura agradável e fluida.'),
(5, 1, 'Um clássico que todo fã deve ler. Trama envolvente e personagens memoráveis.'),
(1, 1, 'Esse mangá é incrível! A história me prendeu desde o primeiro capítulo.'),
(2, 2, 'Adorei os personagens e a arte é fantástica.'),
(3, 3, 'Um dos melhores mangás que já li na vida!'),
(4, 4, 'A trama é envolvente e cheia de reviravoltas.'),
(5, 5, 'Recomendo para todos os fãs de mangás de ação.'),
(1, 2, 'O desenvolvimento dos personagens é excelente.'),
(2, 3, 'A história é cativante e cheia de emoção.'),
(3, 4, 'Não consegui parar de ler até terminar!'),
(4, 5, 'A arte é detalhada e muito bem feita.'),
(5, 1, 'Mal posso esperar pelo próximo volume!'),
(6, 2, 'A narrativa é fluida e fácil de acompanhar.'),
(7, 3, 'Os diálogos são muito bem escritos.'),
(8, 4, 'A ambientação do mangá é incrível.'),
(9, 5, 'Cada capítulo é melhor que o anterior.'),
(10, 1, 'Os vilões são muito bem construídos.'),
(11, 2, 'A ação é constante e emocionante.'),
(12, 3, 'Os personagens secundários também são interessantes.'),
(13, 4, 'A história tem um ritmo perfeito.'),
(14, 5, 'A arte evolui muito ao longo do mangá.'),
(15, 1, 'Um mangá que todo fã deve ler pelo menos uma vez.'),
(6, 3, 'A trama é cheia de surpresas e reviravoltas.'),
(7, 4, 'Os personagens têm profundidade e complexidade.'),
(8, 5, 'A história é emocionante e tocante.'),
(9, 1, 'A arte é simplesmente deslumbrante.'),
(10, 2, 'Cada capítulo me deixou ansioso pelo próximo.'),
(11, 3, 'Os temas abordados são muito relevantes.'),
(12, 4, 'A narrativa é envolvente e cativante.'),
(13, 5, 'Os personagens são memoráveis e únicos.'),
(14, 1, 'A história é cheia de ação e aventura.'),
(15, 2, 'Um mangá que eu recomendo para todos os meus amigos.'),
(1, 3, 'A trama é complexa e muito bem desenvolvida.'),
(2, 4, 'Os personagens têm uma química incrível.'),
(3, 5, 'A arte é detalhada e cheia de vida.'),
(4, 1, 'Cada capítulo é uma nova surpresa.'),
(5, 2, 'A história é emocionante e cheia de reviravoltas.'),
(6, 4, 'Os personagens são profundos e bem construídos.'),
(7, 5, 'A narrativa é fluida e fácil de seguir.'),
(8, 1, 'A ambientação do mangá é fantástica.'),
(9, 2, 'Cada capítulo me deixou querendo mais.'),
(10, 3, 'Os vilões são complexos e interessantes.'),
(11, 4, 'A ação é constante e emocionante.'),
(12, 5, 'Os personagens secundários são tão interessantes quanto os principais.'),
(13, 1, 'A história tem um ritmo perfeito e envolvente.'),
(14, 2, 'A arte evolui muito ao longo do mangá.'),
(15, 3, 'Um mangá que todo fã deve ler pelo menos uma vez na vida.'),
(16, 4, 'A trama é cheia de surpresas e reviravoltas.'),
(17, 5, 'Os personagens têm profundidade e complexidade.'),
(18, 1, 'A história é emocionante e tocante.'),
(19, 2, 'A arte é simplesmente deslumbrante.'),
(20, 3, 'Cada capítulo me deixou ansioso pelo próximo.'),
(21, 4, 'Os temas abordados são muito relevantes.'),
(22, 5, 'A narrativa é envolvente e cativante.'),
(23, 1, 'Os personagens são memoráveis e únicos.'),
(24, 2, 'A história é cheia de ação e aventura.'),
(25, 3, 'Um mangá que eu recomendo para todos os meus amigos.'),
(26, 4, 'A trama é complexa e muito bem desenvolvida.'),
(27, 5, 'Os personagens têm uma química incrível.'),
(28, 1, 'A arte é detalhada e cheia de vida.'),
(29, 2, 'Cada capítulo é uma nova surpresa.'),
(30, 3, 'A história é emocionante e cheia de reviravoltas.'),
(31, 4, 'Os personagens são profundos e bem construídos.'),
(32, 5, 'A narrativa é fluida e fácil de seguir.'),
(33, 1, 'A ambientação do mangá é fantástica.'),
(34, 2, 'Cada capítulo me deixou querendo mais.'),
(35, 3, 'Os vilões são complexos e interessantes.'),
(36, 4, 'A ação é constante e emocionante.'),
(37, 5, 'Os personagens secundários são tão interessantes quanto os principais.'),
(38, 1, 'A história tem um ritmo perfeito e envolvente.'),
(39, 2, 'A arte evolui muito ao longo do mangá.'),
(40, 3, 'Um mangá que todo fã deve ler pelo menos uma vez na vida.'),
(1, 4, 'Incrível mangá! A história e os personagens são fantásticos.'),
(2, 5, 'Adorei a arte e o enredo. Mal posso esperar pelo próximo volume.'),
(3, 1, 'Um dos melhores mangás que já li! A trama é envolvente.'),
(4, 2, 'Ação e aventura na medida certa. Recomendo muito!'),
(5, 3, 'Personagens profundos e uma história cativante. Vale a pena ler.'),
(6, 4, 'A narrativa é fluida e fácil de acompanhar. Gostei muito!'),
(7, 5, 'Os diálogos são muito bem escritos e os personagens são memoráveis.'),
(8, 1, 'A ambientação do mangá é incrível. Cada capítulo é melhor que o anterior.'),
(9, 2, 'Os vilões são muito bem construídos. Ação constante e emocionante!'),
(10, 3, 'Mal posso esperar pelo próximo volume! A arte é impressionante.'),
(11, 4, 'Muito bom, mas alguns personagens poderiam ser mais explorados.'),
(12, 5, 'Leitura agradável e fluida. A história é envolvente.'),
(13, 1, 'Um clássico que todo fã deve ler. Trama envolvente e personagens memoráveis.'),
(14, 2, 'Incrível história e personagens cativantes! Adorei a arte e o enredo.'),
(15, 3, 'Um dos melhores mangás que já li! A trama é profunda e emocionante.'),
(16, 4, 'Boa leitura, mas poderia ser melhor desenvolvida. Personagens profundos e trama envolvente.'),
(17, 5, 'Gostei muito dos temas abordados. Simplesmente fantástico!'),
(18, 1, 'Interessante, mas com alguns clichês. Ação e aventura na medida certa.'),
(19, 2, 'Recomendo para fãs do gênero. Arte impressionante e história emocionante.'),
(20, 3, 'Muito bom, mas alguns personagens poderiam ser mais explorados. Leitura agradável e fluida.'),
(21, 4, 'Um clássico que todo fã deve ler. Trama envolvente e personagens memoráveis.'),
(22, 5, 'Incrível história e personagens cativantes! Adorei a arte e o enredo.'),
(23, 1, 'Um dos melhores mangás que já li! A trama é profunda e emocionante.'),
(24, 2, 'Boa leitura, mas poderia ser melhor desenvolvida. Personagens profundos e trama envolvente.'),
(25, 3, 'Gostei muito dos temas abordados. Simplesmente fantástico!'),
(26, 4, 'Interessante, mas com alguns clichês. Ação e aventura na medida certa.'),
(27, 5, 'Recomendo para fãs do gênero. Arte impressionante e história emocionante.'),
(28, 1, 'Muito bom, mas alguns personagens poderiam ser mais explorados. Leitura agradável e fluida.'),
(29, 2, 'Um clássico que todo fã deve ler. Trama envolvente e personagens memoráveis.'),
(30, 3, 'Incrível história e personagens cativantes! Adorei a arte e o enredo.'),
(31, 4, 'Um dos melhores mangás que já li! A trama é profunda e emocionante.'),
(32, 5, 'Boa leitura, mas poderia ser melhor desenvolvida. Personagens profundos e trama envolvente.'),
(33, 1, 'Gostei muito dos temas abordados. Simplesmente fantástico!'),
(34, 2, 'Interessante, mas com alguns clichês. Ação e aventura na medida certa.'),
(35, 3, 'Recomendo para fãs do gênero. Arte impressionante e história emocionante.'),
(36, 4, 'Muito bom, mas alguns personagens poderiam ser mais explorados. Leitura agradável e fluida.'),
(37, 5, 'Um clássico que todo fã deve ler. Trama envolvente e personagens memoráveis.'),
(38, 1, 'Incrível história e personagens cativantes! Adorei a arte e o enredo.'),
(39, 2, 'Um dos melhores mangás que já li! A trama é profunda e emocionante.'),
(40, 3, 'Boa leitura, mas poderia ser melhor desenvolvida. Personagens profundos e trama envolvente.'),
(1, 5, 'Gostei muito dos temas abordados. Simplesmente fantástico!'),
(2, 4, 'Interessante, mas com alguns clichês. Ação e aventura na medida certa.'),
(3, 3, 'Recomendo para fãs do gênero. Arte impressionante e história emocionante.'),
(4, 2, 'Muito bom, mas alguns personagens poderiam ser mais explorados. Leitura agradável e fluida.'),
(5, 1, 'Um clássico que todo fã deve ler. Trama envolvente e personagens memoráveis.');

INSERT INTO CAPITULOS (MANGAS_ID, NUMERO_CAPITULO, TITULO_CAPITULO, DATA_LANCAMENTO, SINOPSE) VALUES
(1, 1, 'O Início da Aventura', '1997-07-22', 'Monkey D. Luffy começa sua jornada para se tornar o Rei dos Piratas.'),
(2, 1, 'O Nascimento de um Ninja', '1999-09-21', 'Naruto Uzumaki é apresentado como um jovem ninja com grandes sonhos.'),
(3, 1, 'O Ataque dos Titãs', '2009-09-09', 'A humanidade enfrenta a ameaça dos Titãs pela primeira vez.'),
(4, 1, 'A Espada do Caçador de Demônios', '2016-02-15', 'Tanjiro Kamado inicia sua luta contra os demônios para salvar sua irmã.'),
(5, 1, 'O Ceifador de Almas', '2001-08-07', 'Ichigo Kurosaki descobre seus poderes como Ceifador de Almas.'),
(6, 1, 'O Começo da Jornada', '1998-03-03', 'Gon Freecss decide se tornar um Hunter para encontrar seu pai.'),
(7, 1, 'O Primeiro Encontro com um Ghoul', '2011-09-08', 'Kaneki Ken enfrenta sua transformação em meio humano e meio ghoul.'),
(8, 1, 'O Caderno da Morte', '2003-12-01', 'Light Yagami encontra o Death Note e começa sua missão de justiça.'),
(9, 1, 'A Espada do Berserk', '1989-08-25', 'Guts inicia sua jornada sombria em um mundo cheio de demônios.'),
(10, 1, 'A Guerreira da Lua', '1991-03-28', 'Usagi Tsukino descobre seus poderes como Sailor Moon.'),
(11, 1, 'O Teste do Hunter', '1998-03-03', 'Gon Freecss participa do exame para se tornar um Hunter.'),
(12, 1, 'O Pacto com o Demônio', '2006-10-16', 'Ciel Phantomhive faz um pacto com Sebastian Michaelis.'),
(13, 1, 'O Encontro com a Deusa', '1988-09-07', 'Keiichi Morisato conhece a deusa Belldandy.'),
(14, 1, 'A Captura da Primeira Carta', '1996-05-01', 'Sakura Kinomoto começa sua missão de capturar as cartas mágicas.'),
(15, 1, 'O Treinamento de Ranma', '1987-08-07', 'Ranma Saotome inicia seu treinamento nas artes marciais.'),
(1, 2, 'O Pirata Almirante', '1997-08-05', 'Luffy encontra o pirata Almirante pela primeira vez.'),
(2, 2, 'A Promessa de Naruto', '1999-10-05', 'Naruto faz uma promessa importante para seus amigos.'),
(3, 2, 'A Muralha se Abre', '2009-09-23', 'Os Titãs rompem a muralha e invadem a cidade.'),
(4, 2, 'O Treinamento de Tanjiro', '2016-03-01', 'Tanjiro começa seu treinamento para se tornar um caçador de demônios.'),
(5, 2, 'A Batalha na Cidade', '2001-08-21', 'Ichigo enfrenta um poderoso inimigo na cidade.'),
(6, 2, 'O Encontro com Killua', '1998-03-17', 'Gon conhece Killua Zoldyck, que se torna seu amigo.'),
(7, 2, 'A Luta pela Sobrevivência', '2011-09-22', 'Kaneki luta para sobreviver em um mundo perigoso.'),
(8, 2, 'O Primeiro Alvo', '2004-01-15', 'Light escolhe sua primeira vítima com o Death Note.'),
(9, 2, 'A Marca do Destino', '1989-09-08', 'Guts recebe uma marca que o persegue constantemente.'),
(10, 2, 'A Batalha das Sailors', '1991-04-11', 'Sailor Moon enfrenta suas primeiras inimigas.'),
(11, 2, 'O Desafio de Leorio', '1998-03-31', 'Leorio Paradinight enfrenta um desafio difícil no exame Hunter.'),
(12, 2, 'O Segredo de Sebastian', '2006-11-01', 'Ciel começa a desvendar os segredos de seu mordomo demoníaco.'),
(13, 2, 'A Vida com Belldandy', '1988-09-21', 'Keiichi se adapta à vida com a deusa Belldandy.'),
(14, 2, 'A Captura da Segunda Carta', '1996-05-15', 'Sakura captura sua segunda carta mágica.'),
(15, 2, 'O Encontro com Akane', '1987-08-21', 'Ranma conhece Akane Tendo, que se torna sua noiva relutante.'),
(1, 3, 'A Luta contra Buggy', '1997-08-19', 'Luffy enfrenta o pirata Buggy em uma batalha épica.'),
(2, 3, 'O Desafio de Sasuke', '1999-10-19', 'Naruto enfrenta Sasuke Uchiha em um duelo intenso.'),
(3, 3, 'A Defesa da Muralha', '2009-10-07', 'Os sobreviventes tentam defender a muralha dos Titãs.'),
(4, 3, 'A Espada Nichirin', '2016-03-15', 'Tanjiro recebe sua espada especial para caçar demônios.'),
(5, 3, 'A Batalha no Hospital', '2001-09-04', 'Ichigo luta contra inimigos dentro de um hospital.'),
(6, 3, 'O Encontro com Kurapika', '1998-04-14', 'Gon conhece Kurapika, que busca vingança contra os Homens de Preto.'),
(7, 3, 'A Fuga de Kaneki', '2011-10-06', 'Kaneki tenta escapar dos ghouls que o perseguem.'),
(8, 3, 'A Conspiração dos Shinigamis', '2004-01-29', 'Light descobre uma conspiração entre os shinigamis.'),
(9, 3, 'O Encontro com Griffith', '1989-09-22', 'Guts conhece Griffith, líder do Bando do Falcão.'),
(10, 3, 'A Batalha contra Queen Beryl', '1991-04-25', 'Sailor Moon enfrenta a vilã Queen Beryl.'),
(11, 3, 'O Desafio de Kurapika', '1998-04-28', 'Kurapika enfrenta um desafio perigoso no exame Hunter.'),
(12, 3, 'O Passado de Ciel', '2006-11-15', 'Ciel começa a revelar seu passado sombrio.'),
(13, 3, 'A Deusa da Fortuna', '1988-10-05', 'Belldandy traz sorte para a vida de Keiichi.'),
(14, 3, 'A Captura da Terceira Carta', '1996-05-29', 'Sakura captura sua terceira carta mágica.'),
(15, 3, 'O Treinamento de Akane', '1987-09-04', 'Akane começa seu treinamento em artes marciais.'),
(1, 4, 'A Batalha no Baratie', '1997-09-02', 'Luffy enfrenta Don Krieg no restaurante flutuante Baratie.'),
(2, 4, 'A Promessa de Sakura', '1999-11-02', 'Naruto faz uma promessa importante para Sakura Haruno.'),
(3, 4, 'A Retomada da Muralha', '2009-10-21', 'Os humanos planejam retomar a muralha dos Titãs.'),
(4, 4, 'O Encontro com Nezuko', '2016-03-29', 'Tanjiro encontra sua irmã Nezuko, que foi transformada em demônio.'),
(5, 4, 'A Batalha na Soul Society', '2001-09-18', 'Ichigo invade a Soul Society para resgatar Rukia.'),
(6, 4, 'O Encontro com Leorio', '1998-04-28', 'Gon conhece Leorio Paradinight, que sonha em ser médico.'),
(7, 4, 'A Luta contra Touka', '2011-10-20', 'Kaneki enfrenta Touka Kirishima em um confronto intenso.'),
(8, 4, 'A Ascensão de Kira', '2004-02-12', 'Light começa a ser conhecido como Kira.'),
(9, 4, 'A Queda do Bando do Falcão', '1989-10-06', 'O Bando do Falcão enfrenta uma grande derrota.'),
(10, 4, 'A Batalha contra os Shitennou', '1991-05-09', 'Sailor Moon enfrenta os generais Shitennou.'),
(11, 4, 'O Desafio de Gon', '1998-05-12', 'Gon enfrenta um desafio difícil no exame Hunter.'),
(12, 4, 'O Contrato com o Demônio', '2006-11-29', 'Ciel reforça seu contrato com Sebastian.'),
(13, 4, 'A Vida na Terra dos Deuses', '1988-10-19', 'Keiichi explora a vida com as deusas na Terra.'),
(14, 4, 'A Captura da Quarta Carta', '1996-06-12', 'Sakura captura sua quarta carta mágica.'),
(15, 4, 'O Encontro com Shampoo', '1987-09-18', 'Ranma conhece Shampoo, uma guerreira chinesa.'),
(1, 5, 'A Luta contra Arlong', '1997-09-16', 'Luffy enfrenta o pirata Arlong para libertar Nami.'),
(2, 5, 'A Promessa de Sasuke', '1999-11-16', 'Naruto faz uma promessa importante para Sasuke Uchiha.'),
(3, 5, 'A Batalha Final pela Muralha', '2009-11-04', 'Os humanos enfrentam os Titãs na batalha final pela muralha.'),
(4, 5, 'O Treinamento com Urokodaki', '2016-04-12', 'Tanjiro treina com o mestre Urokodaki para se tornar um caçador de demônios.'),
(5, 5, 'A Batalha contra Byakuya', '2001-10-02', 'Ichigo enfrenta Byakuya Kuchiki em uma batalha épica.'),
(6, 5, 'O Encontro com Hisoka', '1998-05-26', 'Gon conhece Hisoka, um misterioso e poderoso Hunter.'),
(7, 5, 'A Fuga de Anteiku', '2011-11-03', 'Kaneki tenta escapar do café Anteiku com seus amigos ghouls.'),
(8, 5, 'A Caçada a Kira', '2004-02-26', 'Light enfrenta a investigação liderada por L para capturá-lo.'),
(9, 5, 'A Ascensão de Griffith', '1989-10-20', 'Griffith começa a ascender ao poder dentro do Bando do Falcão.'),
(10, 5, 'A Batalha contra Nephrite', '1991-05-23', 'Sailor Moon enfrenta o general Nephrite.'),
(11, 5, 'O Desafio de Killua', '1998-06-09', 'Killua Zoldyck enfrenta um desafio perigoso no exame Hunter.'),
(12, 5, 'O Passado de Sebastian', '2006-12-13', 'Sebastian revela mais sobre seu passado demoníaco.'),
(13, 5, 'A Deusa do Amor', '1988-11-02', 'Belldandy ajuda Keiichi em assuntos do coração.'),
(14, 5, 'A Captura da Quinta Carta', '1996-06-26', 'Sakura captura sua quinta carta mágica.'),
(15, 5, 'O Treinamento de Shampoo', '1987-10-02', 'Shampoo começa seu treinamento em artes marciais.'),
(1, 6, 'A Batalha em Alabasta', '1997-10-07', 'Luffy enfrenta Crocodile para salvar o reino de Alabasta.'),
(2, 6, 'A Promessa de Hinata', '1999-12-07', 'Naruto faz uma promessa importante para Hinata Hyuga.'),
(3, 6, 'A Libertação da Muralha', '2009-11-18', 'Os humanos conseguem libertar a muralha dos Titãs.'),
(4, 6, 'O Encontro com Zenitsu', '2016-04-26', 'Tanjiro conhece Zenitsu Agatsuma, um companheiro caçador de demônios.'),
(5, 6, 'A Batalha contra Renji', '2001-10-16', 'Ichigo enfrenta Renji Abarai em uma luta intensa.'),
(6, 6, 'O Encontro com Gon', '1998-06-23', 'Killua conhece Gon Freecss, que se torna seu melhor amigo.'),
(7, 6, 'A Luta contra Rize', '2011-11-17', 'Kaneki enfrenta Rize Kamishiro em um confronto decisivo.'),
(8, 6, 'A Guerra dos Shinigamis', '2004-03-11', 'Light enfrenta uma guerra total entre os shinigamis.'),
(9, 6, 'A Queda de Griffith', '1989-11-03', 'Griffith enfrenta uma grande queda em sua jornada.'),
(10, 6, 'A Batalha contra Zoisite', '1991-06-06', 'Sailor Moon enfrenta o general Zoisite.'),
(11, 6, 'O Desafio de Hisoka', '1998-07-07', 'Hisoka enfrenta um desafio perigoso no exame Hunter.'),
(12, 6, 'O Contrato com Ciel', '2006-12-27', 'Ciel reforça seu contrato com Sebastian para novos desafios.'),
(13, 6, 'A Vida no Mundo dos Deuses', '1988-11-16', 'Keiichi explora mais sobre a vida com as deusas na Terra.'),
(14, 6, 'A Captura da Sexta Carta', '1996-07-10', 'Sakura captura sua sexta carta mágica.'),
(15, 6, 'O Encontro com Ryoga', '1987-10-16', 'Ranma conhece Ryoga Hibiki, um rival em artes marciais.'),
(1, 7 , 'A Luta contra Enel', '1997-10-21', 'Luffy enfrenta o deus Enel para salvar a Ilha Skypiea.'),
(2, 7, 'A Promessa de Shikamaru', '2000-01-04', 'Naruto faz uma promessa importante para Shikamaru Nara.'),
(3, 7, 'A Reconstrução da Muralha', '2009-12-02', 'Os humanos começam a reconstruir a muralha após a guerra.'),
(4, 7, 'O Treinamento com Sakonji', '2016-05-10', 'Tanjiro treina com o mestre Sakonji Urokodaki para aprimorar suas habilidades.'),
(5, 7, 'A Batalha contra Uryu', '2001-10-30', 'Ichigo enfrenta Uryu Ishida em uma luta tensa.'),
(6, 7, 'O Encontro com Leol', '1998-07-21', 'Killua conhece Leol, um membro dos Homens de Preto.'),
(7, 7, 'A Fuga de Cochlea', '2011-12-01', 'Kaneki tenta escapar da prisão de Cochlea com seus aliados ghouls.'),
(8, 7, 'A Revelação de L', '2004-03-25', 'Light descobre a verdadeira identidade de L.'),
(9, 7, 'A Ascensão do Reino de Falconia', '1989-11-17', 'Griffith estabelece o Reino de Falconia como um poder dominante.'),
(10, 7, 'A Batalha contra Kunzite', '1991-06-20', 'Sailor Moon enfrenta o general Kunzite.'),
(11, 7, 'O Desafio de Gon e Killua', '1998-08-04', 'Gon e Killua enfrentam um desafio perigoso juntos no exame Hunter.'),
(12, 7, 'O Passado de Ciel e Sebastian', '2007-01-10', 'Ciel e Sebastian revelam mais sobre seus passados sombrios.'),
(13, 7, 'A Deusa da Sabedoria', '1988-11-30', 'Belldandy ajuda Keiichi com conselhos sábios.'),
(14, 7, 'A Captura da Sexta Carta', '1996-07-10', 'Sakura captura sua sexta carta mágica.'),
(15, 7, 'O Treinamento de Ranma e Akane', '1987-10-16', 'Ranma e Akane treinam juntos para melhorar suas habilidades.'),
(1, 8, 'A Batalha contra Crocodile', '1997-11-04', 'Luffy derrota Crocodile e salva Alabasta.'),
(2, 8, 'A Promessa de Rock Lee', '2000-01-18', 'Naruto faz uma promessa importante para Rock Lee.'),
(3, 8, 'A Paz na Muralha', '2009-12-16', 'A muralha é restaurada e a paz retorna à humanidade.'),
(4, 8, 'O Encontro com Inosuke', '2016-05-24', 'Tanjiro conhece Inosuke Hashibira, um caçador de demônios selvagem.'),
(5, 8, 'A Batalha contra Chad', '2001-11-13', 'Ichigo enfrenta Chad Yasutora em uma luta intensa.'),
(6, 8, 'O Encontro com Bonolenov', '1998-08-18', 'Killua conhece Bonolenov Ndongo, um membro dos Homens de Preto.'),
(7, 8, 'A Luta contra Yamori', '2011-12-15', 'Kaneki enfrenta Yamori em uma batalha brutal.'),
(8, 8, 'A Queda de L', '2004-04-08', 'L enfrenta sua queda final contra Light.'),
(9, 8, 'A Consolidação do Reino de Falconia', '1989-12-01', 'Griffith consolida seu poder no Reino de Falconia.'),
(10, 8, 'A Batalha contra Zoisite e Kunzite', '1991-07-04', 'Sailor Moon enfrenta os generais Zoisite e Kunzite juntos.'),
(11, 8, 'O Desafio Final do Exame Hunter', '1998-08-18', 'Gon e Killua enfrentam o desafio final do exame Hunter.'),
(12, 8, 'O Futuro de Ciel e Sebastian', '2007-01-24', 'Ciel e Sebastian discutem seus planos futuros.'),
(13, 8, 'A Vida com as Deusas na Terra', '1988-12-14', 'Keiichi continua explorando a vida com as deusas na Terra.'),
(14, 8, 'A Captura da Sétima Carta', '1996-07-24', 'Sakura captura sua sétima carta mágica.'),
(15, 8, 'O Treinamento Avançado de Ranma e Akane', '1987-10-30', 'Ranma e Akane avançam em seu treinamento conjunto.'),
(1, 9, 'A Luta contra Lucci', '1997-11-18', 'Luffy enfrenta Rob Lucci para salvar Robin.'),
(2, 9, 'A Promessa de Gaara', '2000-02-01', 'Naruto faz uma promessa importante para Gaara.'),
(3, 9, 'A Celebração na Muralha', '2010-01-06', 'A humanidade celebra a paz restaurada na muralha.'),
(4, 9, 'O Treinamento com Sakonji Urokodaki', '2016-06-07', 'Tanjiro continua seu treinamento com o mestre Urokodaki.'),
(5, 9, 'A Batalha contra Ishida', '2001-11-27', 'Ichigo enfrenta Uryu Ishida novamente em uma luta tensa.'),
(6, 9, 'O Encontro com Shalnark', '1998-09-01', 'Killua conhece Shalnark, um membro dos Homens de Preto.'),
(7, 9, 'A Fuga de Anteiku Parte 2', '2011-12-29', 'Kaneki e seus amigos ghouls continuam sua fuga de Anteiku.'),
(8, 9, 'A Conclusão da Guerra dos Shinigamis', '2004-04-22', 'Light enfrenta a conclusão da guerra entre os shinigamis.'),
(9, 9, 'A Expansão do Reino de Falconia', '1989-12-15', 'Griffith expande seu poder no Reino de Falconia.'),
(10, 9, 'A Batalha contra Nephrite e Zoisite', '1991-07-18', 'Sailor Moon enfrenta os generais Nephrite e Zoisite juntos.'),
(11, 9, 'O Desafio Final de Gon e Killua', '1998-09-15', 'Gon e Killua enfrentam o desafio final juntos no exame Hunter.'),
(12, 9, 'O Futuro Incerto de Ciel e Sebastian', '2007-02-07', 'Ciel e Sebastian discutem seu futuro incerto.'),
(13, 9, 'A Vida com as Deusas na Terra Parte 2', '1988-12-28', 'Keiichi continua explorando a vida com as deusas na Terra.'),
(14, 9, 'A Captura da Oitava Carta', '1996-08-07', 'Sakura captura sua oitava carta mágica.'),
(15, 9, 'O Treinamento Final de Ranma e Akane', '1987-11-13', 'Ranma e Akane concluem seu treinamento conjunto.'),
(1, 10, 'A Batalha contra Kaku', '1997-12-02', 'Luffy enfrenta Kaku na luta para salvar seus amigos.'),
(2, 10, 'A Promessa de Temari', '2000-02-15', 'Naruto faz uma promessa importante para Temari.'),
(3, 10, 'A Renovação da Muralha', '2010-01-20', 'A muralha é renovada e a paz é mantida na humanidade.'),
(4, 10, 'O Encontro com Giyu Tomioka', '2016-06-21', 'Tanjiro conhece Giyu Tomioka, um caçador de demônios de elite.'),
(5, 10, 'A Batalha contra Orihime', '2001-12-11', 'Ichigo enfrenta Orihime Inoue em uma luta emocional.'),
(6, 10, 'O Encontro com Franklin', '1998-09-15', 'Killua conhece Franklin Bordeau, um membro dos Homens de Preto.'),
(7, 10, 'A Luta contra Jason', '2012-01-12', 'Kaneki enfrenta Jason em uma batalha decisiva.'),
(8, 10, 'O Desfecho da Queda de L', '2004-05-06', 'L enfrenta seu desfecho final contra Light.'),
(9, 10, 'A Estabilização do Reino de Falconia', '1989-12-29', 'Griffith estabiliza seu poder no Reino de Falconia.'),
(10, 10, 'A Batalha contra os Shitennou Parte 2', '1991-08-01', 'Sailor Moon enfrenta os generais Shitennou novamente.'),
(11, 10, 'O Desafio Final de Gon e Killua Parte 2', '1998-09-29', 'Gon e Killua enfrentam o desafio final juntos no exame Hunter.'),
(12, 10, 'O Futuro de Ciel e Sebastian Parte 2', '2007-02-21', 'Ciel e Sebastian discutem seus planos futuros novamente.'),
(13, 10, 'A Vida com as Deusas na Terra Parte 3', '1989-01-11', 'Keiichi continua explorando a vida com as deusas na Terra.'),
(14, 10, 'A Captura da Nona Carta', '1996-08-21', 'Sakura captura sua nona carta mágica.'),
(15, 10, 'O Treinamento Avançado de Ranma e Akane Parte 2', '1987-11-27', 'Ranma e Akane continuam avançando em seu treinamento conjunto.'),
(1, 11, 'A Luta contra Lucci Parte 2', '1997-12-16', 'Luffy continua sua luta contra Rob Lucci para salvar Robin.'),
(2, 11, 'A Promessa de Kankuro', '2000-03-07', 'Naruto faz uma promessa importante para Kankuro.'),
(3, 11, 'A Celebração na Muralha Parte 2', '2010-02-03', 'A humanidade continua celebrando a paz restaurada na muralha.'),
(4, 11, 'O Treinamento com Sakonji Urokodaki Parte 2', '2016-07-05', 'Tanjiro continua seu treinamento com o mestre Urokodaki.'),
(5, 11, 'A Batalha contra Ishida Parte 2', '2001-12-25', 'Ichigo enfrenta Uryu Ishida novamente em uma luta tensa.'),
(6, 11, 'O Encontro com Shizuku', '1998-09-29', 'Killua conhece Shizuku Murasaki, um membro dos Homens de Preto.'),
(7, 11, 'A Fuga de Anteiku Parte 3', '2012-01-26', 'Kaneki e seus amigos ghouls continuam sua fuga de Anteiku.'),
(8, 11, 'A Conclusão da Guerra dos Shinigamis Parte 2', '2004-05-20', 'Light enfrenta a conclusão da guerra entre os shinigamis novamente.'),
(9, 11, 'A Expansão do Reino de Falconia Parte 2', '1990-01-12', 'Griffith continua expandindo seu poder no Reino de Falconia.'),
(10, 11, 'A Batalha contra Nephrite e Zoisite Parte 2', '1991-08-15', 'Sailor Moon enfrenta os generais Nephrite e Zoisite novamente.'),
(11, 11, 'O Desafio Final de Gon e Killua Parte 3', '1998-10-13', 'Gon e Killua enfrentam o desafio final juntos no exame Hunter novamente.'),
(12, 11, 'O Futuro Incerto de Ciel e Sebastian Parte 2', '2007-03-07', 'Ciel e Sebastian discutem seu futuro incerto novamente.'),
(13, 11, 'A Vida com as Deusas na Terra Parte 4', '1989-01-25', 'Keiichi continua explorando a vida com as deusas na Terra.'),
(14, 11, 'A Captura da Décima Carta', '1996-09-04', 'Sakura captura sua décima carta mágica.'),
(15, 11, 'O Treinamento Final de Ranma e Akane Parte 2', '1987-12-11', 'Ranma e Akane concluem seu treinamento conjunto novamente.'),
(1, 12, 'A Batalha contra Kaku Parte 2', '1997-12-30', 'Luffy continua sua luta contra Kaku para salvar seus amigos.'),
(2, 12, 'A Promessa de Temari Parte 2', '2000-03-21', 'Naruto faz uma promessa importante para Temari novamente.'),
(3, 12, 'A Renovação da Muralha Parte 2', '2010-02-17', 'A muralha é renovada e a paz é mantida na humanidade novamente.'),
(4, 12, 'O Encontro com Giyu Tomioka Parte 2', '2016-07-19', 'Tanjiro continua conhecendo Giyu Tomioka, um caçador de demônios de elite.'),
(5, 12, 'A Batalha contra Orihime Parte 2', '2002-01-08', 'Ichigo enfrenta Orihime Inoue novamente em uma luta emocional.'),
(6, 12, 'O Encontro com Machi', '1998-10-13', 'Killua conhece Machi Komacine, um membro dos Homens de Preto.'),
(7, 12, 'A Luta contra Jason Parte 2', '2012-02-09', 'Kaneki continua sua luta contra Jason em uma batalha decisiva.'),
(8, 12, 'O Desfecho da Queda de L Parte 2', '2004-06-03', 'L enfrenta seu desfecho final contra Light novamente.'),
(9, 12, 'A Estabilização do Reino de Falconia Parte 2', '1990-01-26', 'Griffith estabiliza seu poder no Reino de Falconia novamente.'),
(10, 12, 'A Batalha contra os Shitennou Parte 3', '1991-08-29', 'Sailor Moon enfrenta os generais Shitennou mais uma vez.'),
(11, 12, 'O Desafio Final de Gon e Killua Parte 4', '1998-10-27', 'Gon e Killua enfrentam o desafio final juntos no exame Hunter mais uma vez.'),
(12, 12, 'O Futuro de Ciel e Sebastian Parte 3', '2007-03-21', 'Ciel e Sebastian discutem seus planos futuros novamente.'),
(13, 12, 'A Vida com as Deusas na Terra Parte 5', '1989-02-08', 'Keiichi continua explorando a vida com as deusas na Terra.'),
(14, 12, 'A Captura da Décima Primeira Carta', '1996-09-18', 'Sakura captura sua décima primeira carta mágica.'),
(15, 12, 'O Treinamento Avançado de Ranma e Akane Parte 3', '1987-12-25', 'Ranma e Akane continuam avançando em seu treinamento conjunto.'),
(1, 13, 'A Luta contra Enel Parte 2', '1998-01-13', 'Luffy continua sua luta contra o deus Enel para salvar a Ilha Skypiea.'),
(2, 13, 'A Promessa de Kankuro Parte 2', '2000-04-04', 'Naruto faz uma promessa importante para Kankuro novamente.'),
(3, 13, 'A Celebração na Muralha Parte 3', '2010-03-03', 'A humanidade continua celebrando a paz restaurada na muralha novamente.'),
(4, 13, 'O Treinamento com Sakonji Urokodaki Parte 3', '2016-08-02', 'Tanjiro continua seu treinamento com o mestre Urokodaki.'),
(5, 13, 'A Batalha contra Ishida Parte 3', '2002-01-22', 'Ichigo enfrenta Uryu Ishida novamente em uma luta tensa.'),
(6, 13, 'O Encontro com Nobunaga', '1998-10-27', 'Killua conhece Nobunaga Hazama, um membro dos Homens de Preto.'),
(7, 13, 'A Fuga de Anteiku Parte 4', '2012-02-23', 'Kaneki e seus amigos ghouls continuam sua fuga de Anteiku.'),
(8, 13, 'A Conclusão da Guerra dos Shinigamis Parte 3', '2004-06-17', 'Light enfrenta a conclusão da guerra entre os shinigamis mais uma vez.'),
(9, 13, 'A Expansão do Reino de Falconia Parte 3', '1990-02-09', 'Griffith continua expandindo seu poder no Reino de Falconia.'),
(10, 13, 'A Batalha contra Nephrite e Zoisite Parte 3', '1991-09-12', 'Sailor Moon enfrenta os generais Nephrite e Zoisite mais uma vez.'),
(11, 13, 'O Desafio Final de Gon e Killua Parte 5', '1998-11-10', 'Gon e Killua enfrentam o desafio final juntos no exame Hunter mais uma vez.'),
(12, 13, 'O Futuro Incerto de Ciel e Sebastian Parte 3', '2007-04-04', 'Ciel e Sebastian discutem seu futuro incerto mais uma vez.'),
(13, 13, 'A Vida com as Deusas na Terra Parte 6', '1989-02-22', 'Keiichi continua explorando a vida com as deusas na Terra.'),
(14, 13, 'A Captura da Décima Segunda Carta', '1996-10-02', 'Sakura captura sua décima segunda carta mágica.'),
(15, 13, 'O Treinamento Final de Ranma e Akane Parte 3', '1988-01-08', 'Ranma e Akane concluem seu treinamento conjunto mais uma vez.'),
(1, 14, 'A Batalha contra Crocodile Parte 2', '1998-01-27', 'Luffy continua sua luta contra Crocodile para salvar Alabasta.'),
(2, 14, 'A Promessa de Gaara Parte 2', '2000-04-18', 'Naruto faz uma promessa importante para Gaara novamente.'),
(3, 14, 'A Paz na Muralha Parte 2', '2010-03-17', 'A muralha é restaurada e a paz retorna à humanidade novamente.'),
(4, 14, 'O Encontro com Inosuke Parte 2', '2016-08-16', 'Tanjiro continua conhecendo Inosuke Hashibira, um caçador de demônios selvagem.'),
(5, 14, 'A Batalha contra Chad Parte 2', '2002-02-05', 'Ichigo enfrenta Chad Yasutora novamente em uma luta intensa.'),
(6, 14, 'O Encontro com Kortopi', '1998-11-10', 'Killua conhece Kortopi, um membro dos Homens de Preto.'),
(7, 14, 'A Luta contra Yamori Parte 2', '2012-03-08', 'Kaneki continua sua luta contra Yamori em uma batalha brutal.'),
(8, 14, 'O Desfecho da Queda de L Parte 3', '2004-07-01', 'L enfrenta seu desfecho final contra Light mais uma vez.'),
(9, 14, 'A Consolidação do Reino de Falconia Parte 2', '1990-02-23', 'Griffith consolida seu poder no Reino de Falconia mais uma vez.'),
(10, 14, 'A Batalha contra os Shitennou Parte 4', '1991-09-26', 'Sailor Moon enfrenta os generais Shitennou mais uma vez.'),
(11, 14, 'O Desafio Final de Gon e Killua Parte 6', '1998-11-24', 'Gon e Killua enfrentam o desafio final juntos no exame Hunter mais uma vez.'),
(12, 14, 'O Futuro de Ciel e Sebastian Parte 4', '2007-04-18', 'Ciel e Sebastian discutem seus planos futuros mais uma vez.'),
(13, 14, 'A Vida com as Deusas na Terra Parte 7', '1989-03-08', 'Keiichi continua explorando a vida com as deusas na Terra.'),
(14, 14, 'A Captura da Décima Terceira Carta', '1996-10-16', 'Sakura captura sua décima terceira carta mágica.'),
(15, 14, 'O Treinamento Avançado de Ranma e Akane Parte 4', '1988-01-22', 'Ranma e Akane continuam avançando em seu treinamento conjunto.'),
(1, 15, 'A Luta contra Lucci Parte 3', '1998-02-10', 'Luffy continua sua luta contra Rob Lucci para salvar Robin.'),
(2, 15, 'A Promessa de Kankuro Parte 3', '2000-05-02', 'Naruto faz uma promessa importante para Kankuro novamente.'),
(3, 15, 'A Celebração na Muralha Parte 4', '2010-03-31', 'A humanidade continua celebrando a paz restaurada na muralha novamente.'),
(4, 15, 'O Treinamento com Sakonji Urokodaki Parte 4', '2016-08-30', 'Tanjiro continua seu treinamento com o mestre Urokodaki.'),
(5, 15, 'A Batalha contra Ishida Parte 4', '2002-02-19', 'Ichigo enfrenta Uryu Ishida novamente em uma luta tensa.'),
(6, 15, 'O Encontro com Feitan', '1998-11-24', 'Killua conhece Feitan Portor, um membro dos Homens de Preto.'),
(7, 15, 'A Fuga de Anteiku Parte 5', '2012-03-22', 'Kaneki e seus amigos ghouls continuam sua fuga de Anteiku.'),
(8, 15, 'A Conclusão da Guerra dos Shinigamis Parte 4', '2004-07-15', 'Light enfrenta a conclusão da guerra entre os shinigamis mais uma vez.'),
(9, 15, 'A Expansão do Reino de Falconia Parte 4', '1990-03-09', 'Griffith continua expandindo seu poder no Reino de Falconia.'),
(10, 15, 'A Batalha contra Nephrite e Zoisite Parte 4', '1991-10-10', 'Sailor Moon enfrenta os generais Nephrite e Zoisite mais uma vez.'),
(11, 15, 'O Desafio Final de Gon e Killua Parte 7', '1998-12-08', 'Gon e Killua enfrentam o desafio final juntos no exame Hunter mais uma vez.'),
(12, 15, 'O Futuro Incerto de Ciel e Sebastian Parte 4', '2007-05-02', 'Ciel e Sebastian discutem seu futuro incerto mais uma vez.'),
(13, 15, 'A Vida com as Deusas na Terra Parte 8', '1989-03-22', 'Keiichi continua explorando a vida com as deusas na Terra.'),
(14, 15, 'A Captura da Décima Quarta Carta', '1996-10-30', 'Sakura captura sua décima quarta carta mágica.'),
(15, 15, 'O Treinamento Final de Ranma e Akane Parte 4', '1988-02-05', 'Ranma e Akane concluem seu treinamento conjunto mais uma vez.'),
(1, 16, 'A Batalha contra Kaku Parte 3', '1998-02-24', 'Luffy continua sua luta contra Kaku para salvar seus amigos.'),
(2, 16, 'A Promessa de Temari Parte 3', '2000-05-16', 'Naruto faz uma promessa importante para Temari novamente.'),
(3, 16, 'A Renovação da Muralha Parte 3', '2010-04-14', 'A muralha é renovada e a paz é mantida na humanidade novamente.'),
(4, 16, 'O Encontro com Giyu Tomioka Parte 3', '2016-09-13', 'Tanjiro continua conhecendo Giyu Tomioka, um caçador de demônios de elite.'),
(5, 16, 'A Batalha contra Orihime Parte 3', '2002-03-05', 'Ichigo enfrenta Orihime Inoue novamente em uma luta emocional.'),
(6, 16, 'O Encontro com Pakunoda', '1998-12-08', 'Killua conhece Pakunoda, um membro dos Homens de Preto.'),
(7, 16, 'A Luta contra Yamori Parte 3', '2012-04-05', 'Kaneki continua sua luta contra Yamori em uma batalha brutal.'),
(8, 16, 'O Desfecho da Queda de L Parte 4', '2004-07-29', 'L enfrenta seu desfecho final contra Light mais uma vez.'),
(9, 16, 'A Consolidação do Reino de Falconia Parte 3', '1990-03-23', 'Griffith consolida seu poder no Reino de Falconia mais uma vez.'),
(10, 16, 'A Batalha contra os Shitennou Parte 5', '1991-11-07', 'Sailor Moon enfrenta os generais Shitennou mais uma vez.'),
(11, 16, 'O Desafio Final de Gon e Killua Parte 8', '1998-12-22', 'Gon e Killua enfrentam o desafio final juntos no exame Hunter mais uma vez.'),
(12, 16, 'O Futuro de Ciel e Sebastian Parte 5', '2007-05-16', 'Ciel e Sebastian discutem seus planos futuros mais uma vez.'),
(13, 16, 'A Vida com as Deusas na Terra Parte 9', '1989-04-05', 'Keiichi continua explorando a vida com as deusas na Terra.'),
(14, 16, 'A Captura da Décima Quinta Carta', '1996-11-13', 'Sakura captura sua décima quinta carta mágica.'),
(15, 16, 'O Treinamento Avançado de Ranma e Akane Parte 5', '1988-02-19', 'Ranma e Akane continuam avançando em seu treinamento conjunto.'),
(16, 16, 'A Luta Final', '1998-03-10', 'Luffy enfrenta seu maior desafio na luta final para proteger seus amigos.'),
(17, 16, 'A Promessa Final', '2000-05-30', 'Naruto faz sua promessa final para proteger seus amigos e vila.'),
(18, 16, 'A Paz Eterna', '2010-04-28', 'A humanidade alcança uma paz eterna após anos de conflito.'),
(19, 16, 'O Mestre dos Caçadores de Demônios', '2016-09-27', 'Tanjiro se torna um mestre entre os caçadores de demônios.'),
(20, 16, 'A Batalha Suprema', '2002-03-19', 'Ichigo enfrenta sua batalha suprema para proteger seus amigos.'),
(21, 16, 'O Último Encontro', '1998-12-22', 'Killua tem um encontro decisivo com um antigo aliado.'),
(22, 16, 'A Libertação Final', '2012-04-19', 'Kaneki alcança sua libertação final como ghoul.'),
(23, 16, 'A Vitória de Light', '2004-08-12', 'Light alcança a vitória final em sua batalha contra L.'),
(24, 16, 'O Reino Eterno de Falconia', '1990-04-06', 'Griffith estabelece Falconia como um reino eterno.'),
(25, 16, 'A Batalha dos Deuses', '1991-11-21', 'Sailor Moon enfrenta a batalha final contra os deuses malignos.');